-- test_library_v1_book.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
-- Source message: test.library.v1.Book
--
-- Add custom queries in queries/custom/ alongside this file.

-- name: GetTestLibraryV1Book :one
SELECT "id", "shelf_id", "author", "title", "read", "created_at", "updated_at"
FROM "test_library_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestLibraryV1Book :many
SELECT "id", "shelf_id", "author", "title", "read", "created_at", "updated_at"
FROM "test_library_v1_book"
ORDER BY "id";

-- name: CreateTestLibraryV1Book :one
INSERT INTO "test_library_v1_book" ("shelf_id", "author", "title", "read")
VALUES ($1, $2, $3, $4)
RETURNING *;

-- name: UpdateTestLibraryV1Book :one
UPDATE "test_library_v1_book"
SET
    "shelf_id" = $1,
    "author" = $2,
    "title" = $3,
    "read" = $4,
    "updated_at" = now()
WHERE "id" = $5
RETURNING *;

-- name: DeleteTestLibraryV1Book :exec
DELETE FROM "test_library_v1_book"
WHERE "id" = $1;