-- test_library_v1_shelf.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
-- Source message: test.library.v1.Shelf
--
-- Add custom queries in queries/custom/ alongside this file.

-- name: GetTestLibraryV1Shelf :one
SELECT "id", "theme", "created_at", "updated_at"
FROM "test_library_v1_shelf"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestLibraryV1Shelf :many
SELECT "id", "theme", "created_at", "updated_at"
FROM "test_library_v1_shelf"
ORDER BY "id";

-- name: CreateTestLibraryV1Shelf :one
INSERT INTO "test_library_v1_shelf" ("theme")
VALUES ($1)
RETURNING *;

-- name: UpdateTestLibraryV1Shelf :one
UPDATE "test_library_v1_shelf"
SET
    "theme" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestLibraryV1Shelf :exec
DELETE FROM "test_library_v1_shelf"
WHERE "id" = $1;