import { isMessage, type MessageInitShape } from "@bufbuild/protobuf";
import { NullValue } from "@bufbuild/protobuf/wkt";
import {
  type Constant,
  ConstantSchema,
  type Expr_Call,
  type Expr_Comprehension,
  type Expr_CreateList,
  type Expr_CreateStruct,
  type Expr_CreateStruct_Entry,
  type Expr_Ident,
  type Expr_Select,
  type Expr as ProtoExpr,
} from "../../gen/cel/expr/syntax_pb.js";

/**
 * ConstantValue mirrors the CEL constant surface.
 */
export type ConstantValue = null | boolean | bigint | number | string | Uint8Array | Constant;

/**
 * ExprKind identifies the active expression variant.
 */
export enum ExprKind {
  Unspecified = 0,
  Call = 1,
  Comprehension = 2,
  Ident = 3,
  List = 4,
  Literal = 5,
  Map = 6,
  Select = 7,
  Struct = 8,
}

/**
 * EntryExprKind identifies the active entry-expression variant.
 */
export enum EntryExprKind {
  Unspecified = 0,
  MapEntry = 1,
  StructField = 2,
}

/**
 * IdGenerator remaps expression ids.
 */
export type IdGenerator = (originalId: number) => number;

/**
 * CallExpr describes a call expression.
 */
export interface CallExpr {
  /** FunctionName returns the name of the function. */
  functionName(): string;
  /** IsMemberFunction returns whether the call has a non-nil target indicating it is a member function. */
  isMemberFunction(): boolean;
  /** Target returns the target of the expression if one is present. */
  target(): Expr;
  /** Args returns the list of call arguments, excluding the target. */
  args(): Expr[];
}

/**
 * ListExpr describes a list creation expression.
 */
export interface ListExpr {
  /** Elements returns the list elements as expressions. */
  elements(): Expr[];
  /** OptionalIndices returns the list of optional indices in the list literal. */
  optionalIndices(): number[];
  /** IsOptional indicates whether the given element index is optional. */
  isOptional(index: number): boolean;
  /** Size returns the number of elements in the list. */
  size(): number;
}

/**
 * SelectExpr describes a select expression.
 */
export interface SelectExpr {
  /** Operand returns the selection operand expression. */
  operand(): Expr;
  /** FieldName returns the field name being selected from the operand. */
  fieldName(): string;
  /** IsTestOnly indicates whether the select expression is a presence test generated by a macro. */
  isTestOnly(): boolean;
}

/**
 * MapEntry describes a map entry expression.
 */
export interface MapEntry {
  /** Key returns the map entry key expression. */
  key(): Expr;
  /** Value returns the map entry value expression. */
  value(): Expr;
  /** IsOptional returns whether the entry is optional. */
  isOptional(): boolean;
}

/**
 * MapExpr describes a map creation expression.
 */
export interface MapExpr {
  /** Entries returns the map key-value pairs as EntryExpr values. */
  entries(): EntryExpr[];
  /** Size returns the number of entries in the map. */
  size(): number;
}

/**
 * StructField describes a struct field initializer.
 */
export interface StructField {
  /** Name returns the name of the field. */
  name(): string;
  /** Value returns the field initialization expression. */
  value(): Expr;
  /** IsOptional returns whether the field is optional. */
  isOptional(): boolean;
}

/**
 * StructExpr describes a struct creation expression.
 */
export interface StructExpr {
  /** TypeName returns the struct type name. */
  typeName(): string;
  /** Fields returns the set of field initializers in the struct expression as EntryExpr values. */
  fields(): EntryExpr[];
}

/**
 * ComprehensionExpr describes a comprehension expression.
 */
export interface ComprehensionExpr {
  /** IterRange returns the range being iterated. */
  iterRange(): Expr;
  /** IterVar returns the first iteration variable name. */
  iterVar(): string;
  /** IterVar2 returns the second iteration variable name, if present. */
  iterVar2(): string;
  /** AccuVar returns the accumulator variable name. */
  accuVar(): string;
  /** AccuInit returns the accumulator initialization expression. */
  accuInit(): Expr;
  /** LoopCondition returns the loop condition expression. */
  loopCondition(): Expr;
  /** LoopStep returns the loop step expression. */
  loopStep(): Expr;
  /** Result returns the result expression. */
  result(): Expr;
}

/**
 * EntryExpr describes a map-entry or struct-field expression.
 */
export interface EntryExpr {
  /** Id of the entry as it appears in the AST. */
  id(): number;
  /** Kind of the entry expression node. See EntryExprKind for valid enum values. */
  kind(): EntryExprKind;
  /** AsMapEntry casts the EntryExpr to a MapEntry. */
  asMapEntry(): MapEntry | undefined;
  /** AsStructField casts the EntryExpr to a StructField. */
  asStructField(): StructField | undefined;
  /** RenumberIds performs an in-place update of the entry and its descendant numeric ids. */
  renumberIds(generator: IdGenerator): void;
  /** ToProto converts the entry expression to protobuf form. */
  toProto(): Expr_CreateStruct_Entry;
}

/**
 * Expr describes a CEL expression.
 */
export interface Expr {
  /** Id of the expression as it appears in the AST. */
  id(): number;
  /** Kind of the expression node. See ExprKind for the valid enum values. */
  kind(): ExprKind;
  /** AsCall adapts the expr into a CallExpr. */
  asCall(): CallExpr | undefined;
  /** AsComprehension adapts the expr into a ComprehensionExpr. */
  asComprehension(): ComprehensionExpr | undefined;
  /** AsIdent adapts the expr into an identifier string. */
  asIdent(): string | undefined;
  /** AsLiteral adapts the expr into a literal constant value. */
  asLiteral(): ConstantValue | undefined;
  /** AsList adapts the expr into a ListExpr. */
  asList(): ListExpr | undefined;
  /** AsMap adapts the expr into a MapExpr. */
  asMap(): MapExpr | undefined;
  /** AsSelect adapts the expr into a SelectExpr. */
  asSelect(): SelectExpr | undefined;
  /** AsStruct adapts the expr into a StructExpr. */
  asStruct(): StructExpr | undefined;
  /** RenumberIds performs an in-place update of the expression and all of its descendant numeric ids. */
  renumberIds(generator: IdGenerator): void;
  /**
   * SetKindCase replaces the contents of the current expression with the contents of the other.
   *
   * This method should only be used during AST rewrites using temporary Expr values.
   */
  setKindCase(other?: Expr): void;
  /** ToProto converts the expression to protobuf form. */
  toProto(): ProtoExpr;
  /** Children returns the direct child expressions. */
  children(): Expr[];
}

const SAFE_CALL: CallExpr = {
  functionName: () => "",
  isMemberFunction: () => false,
  target: () => unspecifiedExpr(),
  args: () => [],
};

const SAFE_COMPREHENSION: ComprehensionExpr = {
  iterRange: () => unspecifiedExpr(),
  iterVar: () => "",
  iterVar2: () => "",
  accuVar: () => "",
  accuInit: () => unspecifiedExpr(),
  loopCondition: () => unspecifiedExpr(),
  loopStep: () => unspecifiedExpr(),
  result: () => unspecifiedExpr(),
};

const SAFE_LIST: ListExpr = {
  elements: () => [],
  optionalIndices: () => [],
  isOptional: () => false,
  size: () => 0,
};

const SAFE_SELECT: SelectExpr = {
  operand: () => unspecifiedExpr(),
  fieldName: () => "",
  isTestOnly: () => false,
};

const SAFE_MAP_ENTRY: MapEntry = {
  key: () => unspecifiedExpr(),
  value: () => unspecifiedExpr(),
  isOptional: () => false,
};

const SAFE_MAP: MapExpr = {
  entries: () => [],
  size: () => 0,
};

const SAFE_STRUCT_FIELD: StructField = {
  name: () => "",
  value: () => unspecifiedExpr(),
  isOptional: () => false,
};

const SAFE_STRUCT: StructExpr = {
  typeName: () => "",
  fields: () => [],
};

function cloneConstantValue(value: ConstantValue | undefined): ConstantValue | undefined {
  if (value === undefined || value === null) {
    return value;
  }
  if (value instanceof Uint8Array) {
    return new Uint8Array(value);
  }
  if (typeof value === "object" && "$typeName" in value) {
    return structuredClone(value as MessageInitShape<never>) as Constant;
  }
  return value;
}

function hasSupportedConstantKind(constant: Constant): boolean {
  switch (constant.constantKind.case) {
    case "nullValue":
    case "boolValue":
    case "int64Value":
    case "uint64Value":
    case "doubleValue":
    case "stringValue":
    case "bytesValue":
      return true;
    default:
      return false;
  }
}

function constantValueToProto(value: ConstantValue | undefined): Constant | undefined {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return {
      $typeName: "cel.expr.Constant",
      constantKind: { case: "nullValue", value: NullValue.NULL_VALUE },
    };
  }
  if (typeof value === "boolean") {
    return { $typeName: "cel.expr.Constant", constantKind: { case: "boolValue", value } };
  }
  if (typeof value === "bigint") {
    return { $typeName: "cel.expr.Constant", constantKind: { case: "int64Value", value } };
  }
  if (typeof value === "number") {
    return { $typeName: "cel.expr.Constant", constantKind: { case: "doubleValue", value } };
  }
  if (typeof value === "string") {
    return { $typeName: "cel.expr.Constant", constantKind: { case: "stringValue", value } };
  }
  if (value instanceof Uint8Array) {
    return {
      $typeName: "cel.expr.Constant",
      constantKind: { case: "bytesValue", value: new Uint8Array(value) },
    };
  }
  if (isMessage(value, ConstantSchema) && hasSupportedConstantKind(value)) {
    return structuredClone(value);
  }
  return undefined;
}

/**
 * ProtoConstantToValue converts a protobuf constant to the local representation.
 */
export function protoConstantToValue(constant?: Constant): ConstantValue | undefined {
  if (!constant) {
    return undefined;
  }
  switch (constant.constantKind.case) {
    case "nullValue":
      return null;
    case "boolValue":
    case "stringValue":
    case "bytesValue":
      return constant.constantKind.value instanceof Uint8Array
        ? new Uint8Array(constant.constantKind.value)
        : constant.constantKind.value;
    case "int64Value":
      return constant.constantKind.value;
    case "uint64Value":
      return constant.constantKind.value;
    case "doubleValue":
      return constant.constantKind.value;
    default:
      return undefined;
  }
}

/**
 * ValToConstant converts a local constant value to protobuf constant form.
 */
export function valToConstant(value: ConstantValue): Constant {
  const converted = constantValueToProto(value);
  if (!converted) {
    throw new Error("unsupported constant value");
  }
  return converted;
}

/**
 * ConstantToVal converts a protobuf constant to the local constant representation.
 */
export function constantToVal(constant?: Constant): ConstantValue {
  const converted = protoConstantToValue(constant);
  if (converted === undefined) {
    throw new Error("unsupported constant");
  }
  return converted;
}

/**
 * BaseExpr provides the shared expression implementation.
 */
export class BaseExpr implements Expr {
  protected proto: ProtoExpr;
  protected variant:
    | CallExpr
    | ComprehensionExpr
    | ListExpr
    | MapExpr
    | SelectExpr
    | StructExpr
    | string
    | ConstantValue
    | undefined;
  protected exprKind: ExprKind;

  constructor(proto: ProtoExpr, exprKind: ExprKind, variant?: BaseExpr["variant"]) {
    this.proto = proto;
    this.exprKind = exprKind;
    this.variant = variant;
  }

  /** Id returns the expression id. */
  public id(): number {
    return Number(this.proto.id ?? 0n);
  }

  /** Kind returns the active expression kind. */
  public kind(): ExprKind {
    return this.exprKind;
  }

  public asCall(): CallExpr | undefined {
    return this.exprKind === ExprKind.Call ? (this.variant as CallExpr) : SAFE_CALL;
  }

  public asComprehension(): ComprehensionExpr | undefined {
    return this.exprKind === ExprKind.Comprehension
      ? (this.variant as ComprehensionExpr)
      : SAFE_COMPREHENSION;
  }

  public asIdent(): string | undefined {
    return this.exprKind === ExprKind.Ident ? (this.variant as string) : undefined;
  }

  public asLiteral(): ConstantValue | undefined {
    return this.exprKind === ExprKind.Literal
      ? cloneConstantValue(this.variant as ConstantValue)
      : undefined;
  }

  public asList(): ListExpr | undefined {
    return this.exprKind === ExprKind.List ? (this.variant as ListExpr) : SAFE_LIST;
  }

  public asMap(): MapExpr | undefined {
    return this.exprKind === ExprKind.Map ? (this.variant as MapExpr) : SAFE_MAP;
  }

  public asSelect(): SelectExpr | undefined {
    return this.exprKind === ExprKind.Select ? (this.variant as SelectExpr) : SAFE_SELECT;
  }

  public asStruct(): StructExpr | undefined {
    return this.exprKind === ExprKind.Struct ? (this.variant as StructExpr) : SAFE_STRUCT;
  }

  public renumberIds(generator: IdGenerator): void {
    this.proto.id = BigInt(generator(this.id()));
    if (this.exprKind === ExprKind.Map) {
      for (const entry of this.asMap()?.entries() ?? []) {
        entry.renumberIds(generator);
      }
      return;
    }
    if (this.exprKind === ExprKind.Struct) {
      for (const field of this.asStruct()?.fields() ?? []) {
        field.renumberIds(generator);
      }
      return;
    }
    for (const child of this.children()) {
      child.renumberIds(generator);
    }
  }

  /** SetKindCase replaces the underlying protobuf expression. */
  public setKindCase(other?: Expr): void {
    const id = this.id();
    const replacement = protoToExpr(other?.toProto());
    this.proto = replacement.toProto();
    this.proto.id = BigInt(id);
    this.exprKind = (replacement as BaseExpr).exprKind;
    this.variant = (replacement as BaseExpr).variant;
  }

  /** ToProto converts the expression to protobuf form. */
  public toProto(): ProtoExpr {
    const base = {
      $typeName: "cel.expr.Expr" as const,
      id: BigInt(this.id()),
    };
    switch (this.exprKind) {
      case ExprKind.Call: {
        const call = this.asCall()!;
        return {
          ...base,
          exprKind: {
            case: "callExpr",
            value: {
              $typeName: "cel.expr.Expr.Call",
              function: call.functionName(),
              args: call.args().map((arg) => arg.toProto()),
              target: call.isMemberFunction() ? call.target().toProto() : undefined,
            },
          },
        };
      }
      case ExprKind.Comprehension: {
        const comprehension = this.asComprehension()!;
        return {
          ...base,
          exprKind: {
            case: "comprehensionExpr",
            value: {
              $typeName: "cel.expr.Expr.Comprehension",
              iterRange: comprehension.iterRange().toProto(),
              iterVar: comprehension.iterVar(),
              iterVar2: comprehension.iterVar2(),
              accuVar: comprehension.accuVar(),
              accuInit: comprehension.accuInit().toProto(),
              loopCondition: comprehension.loopCondition().toProto(),
              loopStep: comprehension.loopStep().toProto(),
              result: comprehension.result().toProto(),
            },
          },
        };
      }
      case ExprKind.Ident:
        return {
          ...base,
          exprKind: {
            case: "identExpr",
            value: { $typeName: "cel.expr.Expr.Ident", name: this.asIdent() ?? "" },
          },
        };
      case ExprKind.List: {
        const list = this.asList()!;
        return {
          ...base,
          exprKind: {
            case: "listExpr",
            value: {
              $typeName: "cel.expr.Expr.CreateList",
              elements: list.elements().map((element) => element.toProto()),
              optionalIndices: list.optionalIndices(),
            },
          },
        };
      }
      case ExprKind.Literal:
        return {
          ...base,
          exprKind: {
            case: "constExpr",
            value: constantValueToProto(this.asLiteral()) ?? {
              $typeName: "cel.expr.Constant",
              constantKind: { case: undefined },
            },
          },
        };
      case ExprKind.Map: {
        const map = this.asMap()!;
        return {
          ...base,
          exprKind: {
            case: "structExpr",
            value: {
              $typeName: "cel.expr.Expr.CreateStruct",
              messageName: "",
              entries: map.entries().map((entry) => entry.toProto()),
            },
          },
        };
      }
      case ExprKind.Select: {
        const select = this.asSelect()!;
        return {
          ...base,
          exprKind: {
            case: "selectExpr",
            value: {
              $typeName: "cel.expr.Expr.Select",
              operand: select.operand().toProto(),
              field: select.fieldName(),
              testOnly: select.isTestOnly(),
            },
          },
        };
      }
      case ExprKind.Struct: {
        const struct = this.asStruct()!;
        return {
          ...base,
          exprKind: {
            case: "structExpr",
            value: {
              $typeName: "cel.expr.Expr.CreateStruct",
              messageName: struct.typeName(),
              entries: struct.fields().map((field) => field.toProto()),
            },
          },
        };
      }
      default:
        return { ...base, exprKind: { case: undefined } };
    }
  }

  /** Children returns the direct child expressions. */
  public children(): Expr[] {
    switch (this.exprKind) {
      case ExprKind.Call: {
        const call = this.asCall();
        return call ? [...(call.isMemberFunction() ? [call.target()] : []), ...call.args()] : [];
      }
      case ExprKind.Comprehension: {
        const comp = this.asComprehension();
        return comp
          ? [
              comp.iterRange(),
              comp.accuInit(),
              comp.loopCondition(),
              comp.loopStep(),
              comp.result(),
            ]
          : [];
      }
      case ExprKind.List:
        return this.asList()?.elements() ?? [];
      case ExprKind.Map:
        return (this.asMap()?.entries() ?? []).flatMap((entry) => {
          const mapEntry = entry.asMapEntry();
          return mapEntry ? [mapEntry.key(), mapEntry.value()] : [];
        });
      case ExprKind.Select: {
        const select = this.asSelect();
        return select ? [select.operand()] : [];
      }
      case ExprKind.Struct:
        return (this.asStruct()?.fields() ?? []).flatMap((entry) => {
          const field = entry.asStructField();
          return field ? [field.value()] : [];
        });
      default:
        return [];
    }
  }
}

/**
 * BaseEntryExpr provides the shared entry-expression implementation.
 */
class BaseEntryExpr implements EntryExpr {
  constructor(
    private idValue: number,
    private readonly entryKind: EntryExprKind,
    private readonly mapEntryValue?: MapEntry,
    private readonly structFieldValue?: StructField,
  ) {}

  public id(): number {
    return this.idValue;
  }

  public kind(): EntryExprKind {
    return this.entryKind;
  }

  public asMapEntry(): MapEntry | undefined {
    return this.entryKind === EntryExprKind.MapEntry ? this.mapEntryValue : SAFE_MAP_ENTRY;
  }

  public asStructField(): StructField | undefined {
    return this.entryKind === EntryExprKind.StructField ? this.structFieldValue : SAFE_STRUCT_FIELD;
  }

  public renumberIds(generator: IdGenerator): void {
    this.idValue = generator(this.idValue);
    if (this.entryKind === EntryExprKind.MapEntry) {
      const mapEntry = this.asMapEntry()!;
      mapEntry.key().renumberIds(generator);
      mapEntry.value().renumberIds(generator);
    }
    if (this.entryKind === EntryExprKind.StructField) {
      const structField = this.asStructField()!;
      structField.value().renumberIds(generator);
    }
  }

  public toProto(): Expr_CreateStruct_Entry {
    if (this.entryKind === EntryExprKind.MapEntry) {
      const mapEntry = this.asMapEntry()!;
      return {
        $typeName: "cel.expr.Expr.CreateStruct.Entry",
        id: BigInt(this.idValue),
        keyKind: { case: "mapKey", value: mapEntry.key().toProto() },
        value: mapEntry.value().toProto(),
        optionalEntry: mapEntry.isOptional(),
      };
    }
    const structField = this.asStructField()!;
    return {
      $typeName: "cel.expr.Expr.CreateStruct.Entry",
      id: BigInt(this.idValue),
      keyKind: { case: "fieldKey", value: structField?.name() ?? "" },
      value: structField?.value().toProto(),
      optionalEntry: structField?.isOptional() ?? false,
    };
  }
}

/**
 * UnspecifiedExpr creates an unspecified expression.
 */
export function unspecifiedExpr(id = 0): Expr {
  return new BaseExpr(
    { $typeName: "cel.expr.Expr", id: BigInt(id), exprKind: { case: undefined } },
    ExprKind.Unspecified,
  );
}

/**
 * IdentExpr creates an identifier expression.
 */
export function identExpr(id: number, name: string): Expr {
  const ident: Expr_Ident = { $typeName: "cel.expr.Expr.Ident", name };
  return new BaseExpr(
    {
      $typeName: "cel.expr.Expr",
      id: BigInt(id),
      exprKind: { case: "identExpr", value: ident },
    },
    ExprKind.Ident,
    name,
  );
}

/**
 * LiteralExpr creates a literal expression.
 */
export function literalExpr(id: number, value: ConstantValue): Expr {
  const literal = constantValueToProto(value)!;
  const variant =
    typeof value === "object" && value !== null && "$typeName" in value
      ? cloneConstantValue(value)
      : (protoConstantToValue(literal) ?? value);
  return new BaseExpr(
    {
      $typeName: "cel.expr.Expr",
      id: BigInt(id),
      exprKind: { case: "constExpr", value: literal },
    },
    ExprKind.Literal,
    variant,
  );
}

/**
 * CallExpr creates a call expression.
 */
export function callExpr(id: number, functionName: string, args: Expr[], target?: Expr): Expr {
  const value: Expr_Call = {
    $typeName: "cel.expr.Expr.Call",
    function: functionName,
    args: args.map((arg) => arg.toProto()),
    target: target?.toProto(),
  };
  const call: CallExpr = {
    functionName: () => functionName,
    isMemberFunction: () => target !== undefined,
    target: () => target ?? unspecifiedExpr(),
    args: () => [...args],
  };
  return new BaseExpr(
    {
      $typeName: "cel.expr.Expr",
      id: BigInt(id),
      exprKind: { case: "callExpr", value },
    },
    ExprKind.Call,
    call,
  );
}

/**
 * SelectExpr creates a select expression.
 */
export function selectExpr(id: number, operand: Expr, field: string, testOnly = false): Expr {
  const value: Expr_Select = {
    $typeName: "cel.expr.Expr.Select",
    operand: operand.toProto(),
    field,
    testOnly,
  };
  const select: SelectExpr = {
    operand: () => operand,
    fieldName: () => field,
    isTestOnly: () => testOnly,
  };
  return new BaseExpr(
    {
      $typeName: "cel.expr.Expr",
      id: BigInt(id),
      exprKind: { case: "selectExpr", value },
    },
    ExprKind.Select,
    select,
  );
}

/**
 * ListExpr creates a list expression.
 */
export function listExpr(id: number, elements: Expr[], optionalIndices: number[]): Expr {
  const value: Expr_CreateList = {
    $typeName: "cel.expr.Expr.CreateList",
    elements: elements.map((element) => element.toProto()),
    optionalIndices,
  };
  const list: ListExpr = {
    elements: () => [...elements],
    optionalIndices: () => [...optionalIndices],
    isOptional: (index) => optionalIndices.includes(index),
    size: () => elements.length,
  };
  return new BaseExpr(
    {
      $typeName: "cel.expr.Expr",
      id: BigInt(id),
      exprKind: { case: "listExpr", value },
    },
    ExprKind.List,
    list,
  );
}

/**
 * MapEntryExpr creates a map-entry expression.
 */
export function mapEntryExpr(id: number, key: Expr, value: Expr, optional: boolean): EntryExpr {
  return new BaseEntryExpr(id, EntryExprKind.MapEntry, {
    key: () => key,
    value: () => value,
    isOptional: () => optional,
  });
}

/**
 * StructFieldExpr creates a struct-field expression.
 */
export function structFieldExpr(
  id: number,
  name: string,
  value: Expr,
  optional: boolean,
): EntryExpr {
  return new BaseEntryExpr(id, EntryExprKind.StructField, undefined, {
    name: () => name,
    value: () => value,
    isOptional: () => optional,
  });
}

/**
 * MapExpr creates a map expression.
 */
export function mapExpr(id: number, entries: EntryExpr[]): Expr {
  const value: Expr_CreateStruct = {
    $typeName: "cel.expr.Expr.CreateStruct",
    messageName: "",
    entries: entries.map((entry) => entry.toProto()),
  };
  const mapExpr: MapExpr = {
    entries: () => [...entries],
    size: () => entries.length,
  };
  return new BaseExpr(
    {
      $typeName: "cel.expr.Expr",
      id: BigInt(id),
      exprKind: { case: "structExpr", value },
    },
    ExprKind.Map,
    mapExpr,
  );
}

/**
 * StructExpr creates a struct expression.
 */
export function structExpr(id: number, typeName: string, fields: EntryExpr[]): Expr {
  const value: Expr_CreateStruct = {
    $typeName: "cel.expr.Expr.CreateStruct",
    messageName: typeName,
    entries: fields.map((entry) => entry.toProto()),
  };
  const structExpr: StructExpr = {
    typeName: () => typeName,
    fields: () => [...fields],
  };
  return new BaseExpr(
    {
      $typeName: "cel.expr.Expr",
      id: BigInt(id),
      exprKind: { case: "structExpr", value },
    },
    ExprKind.Struct,
    structExpr,
  );
}

/**
 * ComprehensionExpr creates a comprehension expression.
 */
export function comprehensionExpr(
  id: number,
  iterRange: Expr,
  iterVar: string,
  iterVar2: string,
  accuVar: string,
  accuInit: Expr,
  loopCondition: Expr,
  loopStep: Expr,
  result: Expr,
): Expr {
  const value: Expr_Comprehension = {
    $typeName: "cel.expr.Expr.Comprehension",
    iterRange: iterRange.toProto(),
    iterVar,
    iterVar2,
    accuVar,
    accuInit: accuInit.toProto(),
    loopCondition: loopCondition.toProto(),
    loopStep: loopStep.toProto(),
    result: result.toProto(),
  };
  const comprehension: ComprehensionExpr = {
    iterRange: () => iterRange,
    iterVar: () => iterVar,
    iterVar2: () => iterVar2,
    accuVar: () => accuVar,
    accuInit: () => accuInit,
    loopCondition: () => loopCondition,
    loopStep: () => loopStep,
    result: () => result,
  };
  return new BaseExpr(
    {
      $typeName: "cel.expr.Expr",
      id: BigInt(id),
      exprKind: { case: "comprehensionExpr", value },
    },
    ExprKind.Comprehension,
    comprehension,
  );
}

/**
 * EntryExprToProto converts an entry expression to protobuf form.
 */
export function entryExprToProto(entry: EntryExpr): Expr_CreateStruct_Entry {
  return (entry as BaseEntryExpr).toProto();
}

/**
 * ProtoToEntryExpr converts a protobuf entry to the local representation.
 */
export function protoToEntryExpr(entry?: Expr_CreateStruct_Entry): EntryExpr {
  if (!entry) {
    return new BaseEntryExpr(0, EntryExprKind.Unspecified);
  }
  if (entry.keyKind.case === "fieldKey") {
    return structFieldExpr(
      Number(entry.id),
      entry.keyKind.value,
      protoToExpr(entry.value),
      entry.optionalEntry,
    );
  }
  return mapEntryExpr(
    Number(entry.id),
    protoToExpr(entry.keyKind.value),
    protoToExpr(entry.value),
    entry.optionalEntry,
  );
}

/**
 * ProtoToExpr converts a protobuf expression to the local representation.
 */
export function protoToExpr(expr?: ProtoExpr): Expr {
  if (!expr) {
    return unspecifiedExpr();
  }
  switch (expr.exprKind.case) {
    case "identExpr":
      return identExpr(Number(expr.id), expr.exprKind.value.name);
    case "constExpr":
      if (expr.exprKind.value.constantKind.case === "uint64Value") {
        return literalExpr(Number(expr.id), structuredClone(expr.exprKind.value));
      }
      {
        const value = protoConstantToValue(expr.exprKind.value);
        return literalExpr(Number(expr.id), value === undefined ? expr.exprKind.value : value);
      }
    case "callExpr":
      return callExpr(
        Number(expr.id),
        expr.exprKind.value.function,
        expr.exprKind.value.args.map((arg) => protoToExpr(arg)),
        expr.exprKind.value.target ? protoToExpr(expr.exprKind.value.target) : undefined,
      );
    case "selectExpr":
      return selectExpr(
        Number(expr.id),
        protoToExpr(expr.exprKind.value.operand),
        expr.exprKind.value.field,
        expr.exprKind.value.testOnly,
      );
    case "listExpr":
      return listExpr(
        Number(expr.id),
        expr.exprKind.value.elements.map((element) => protoToExpr(element)),
        [...expr.exprKind.value.optionalIndices],
      );
    case "structExpr":
      if (expr.exprKind.value.messageName) {
        return structExpr(
          Number(expr.id),
          expr.exprKind.value.messageName,
          expr.exprKind.value.entries.map((entry) => protoToEntryExpr(entry)),
        );
      }
      return mapExpr(
        Number(expr.id),
        expr.exprKind.value.entries.map((entry) => protoToEntryExpr(entry)),
      );
    case "comprehensionExpr":
      return comprehensionExpr(
        Number(expr.id),
        protoToExpr(expr.exprKind.value.iterRange),
        expr.exprKind.value.iterVar,
        expr.exprKind.value.iterVar2,
        expr.exprKind.value.accuVar,
        protoToExpr(expr.exprKind.value.accuInit),
        protoToExpr(expr.exprKind.value.loopCondition),
        protoToExpr(expr.exprKind.value.loopStep),
        protoToExpr(expr.exprKind.value.result),
      );
    default:
      return unspecifiedExpr(Number(expr.id));
  }
}
