export {
  AST,
  ast,
  checkedAst,
  copyAst,
  copySourceInfo,
  type Extension,
  ExtensionComponent,
  type ExtensionVersion,
  exprToProto,
  extension,
  extensionVersion,
  functionReference,
  heights,
  identReference,
  maxId,
  type OffsetRange,
  postOrderVisit,
  preOrderVisit,
  protoToReferenceInfo,
  protoToSourceInfo,
  ReferenceInfo,
  referenceInfoToProto,
  SourceInfo,
  sourceInfo,
  sourceInfoToProto,
  toAst,
  toProto,
} from "./ast.js";
export {
  type CallExpr,
  type ComprehensionExpr,
  type ConstantValue,
  callExpr,
  comprehensionExpr,
  constantToVal,
  type EntryExpr,
  EntryExprKind,
  type Expr,
  ExprKind,
  entryExprToProto,
  type IdGenerator,
  identExpr,
  type ListExpr,
  listExpr,
  literalExpr,
  type MapEntry,
  type MapExpr,
  mapEntryExpr,
  mapExpr,
  protoConstantToValue,
  protoToEntryExpr,
  protoToExpr,
  type SelectExpr,
  type StructExpr,
  type StructField,
  selectExpr,
  structExpr,
  structFieldExpr,
  unspecifiedExpr,
  valToConstant,
} from "./expr.js";
export { type ExprFactory, exprFactory, exprFactoryWithAccumulator } from "./factory.js";
export {
  allMatcher,
  constantValueMatcher,
  functionMatcher,
  kindMatcher,
  matchDescendants,
  matchSubset,
  type NavigableExpr,
  navigateAst,
  navigateExpr,
} from "./navigable.js";
