-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: mysql
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.library.v1.Shelf
CREATE TABLE IF NOT EXISTS `test_library_v1_shelf` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    `theme` TEXT NOT NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`)
);
CREATE INDEX IF NOT EXISTS `idx_test_library_v1_shelf_theme` ON `test_library_v1_shelf` (`theme`);

-- test.library.v1.Book
CREATE TABLE IF NOT EXISTS `test_library_v1_book` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    `shelf_id` BIGINT UNSIGNED NOT NULL,
    `author` TEXT NOT NULL,
    `title` TEXT NOT NULL,
    `read` TINYINT(1) NOT NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_test_library_v1_book_shelf_id` FOREIGN KEY (`shelf_id`) REFERENCES `test_library_v1_shelf` (`id`) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS `idx_test_library_v1_book_author` ON `test_library_v1_book` (`author`);
CREATE INDEX IF NOT EXISTS `idx_test_library_v1_book_shelf_id` ON `test_library_v1_book` (`shelf_id`);