-- test_library_v1_book.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: mysql
-- Source message: test.library.v1.Book
--
-- Add custom queries in queries/custom/ alongside this file.

-- name: GetTestLibraryV1Book :one
SELECT `id`, `shelf_id`, `author`, `title`, `read`, `created_at`, `updated_at`
FROM `test_library_v1_book`
WHERE `id` = ?
LIMIT 1;

-- name: ListTestLibraryV1Book :many
SELECT `id`, `shelf_id`, `author`, `title`, `read`, `created_at`, `updated_at`
FROM `test_library_v1_book`
ORDER BY `id`;

-- name: CreateTestLibraryV1Book :execresult
INSERT INTO `test_library_v1_book` (`shelf_id`, `author`, `title`, `read`)
VALUES (?, ?, ?, ?);

-- name: GetTestLibraryV1BookByLastInsert :one
SELECT * FROM `test_library_v1_book` WHERE `id` = LAST_INSERT_ID()
LIMIT 1;

-- name: UpdateTestLibraryV1Book :exec
UPDATE `test_library_v1_book`
SET
    `shelf_id` = ?,
    `author` = ?,
    `title` = ?,
    `read` = ?,
    `updated_at` = CURRENT_TIMESTAMP(6)
WHERE `id` = ?;

-- name: DeleteTestLibraryV1Book :exec
DELETE FROM `test_library_v1_book`
WHERE `id` = ?;