-- test_library_v1_shelf.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: mysql
-- Source message: test.library.v1.Shelf
--
-- Add custom queries in queries/custom/ alongside this file.

-- name: GetTestLibraryV1Shelf :one
SELECT `id`, `theme`, `created_at`, `updated_at`
FROM `test_library_v1_shelf`
WHERE `id` = ?
LIMIT 1;

-- name: ListTestLibraryV1Shelf :many
SELECT `id`, `theme`, `created_at`, `updated_at`
FROM `test_library_v1_shelf`
ORDER BY `id`;

-- name: CreateTestLibraryV1Shelf :execresult
INSERT INTO `test_library_v1_shelf` (`theme`)
VALUES (?);

-- name: GetTestLibraryV1ShelfByLastInsert :one
SELECT * FROM `test_library_v1_shelf` WHERE `id` = LAST_INSERT_ID()
LIMIT 1;

-- name: UpdateTestLibraryV1Shelf :exec
UPDATE `test_library_v1_shelf`
SET
    `theme` = ?,
    `updated_at` = CURRENT_TIMESTAMP(6)
WHERE `id` = ?;

-- name: DeleteTestLibraryV1Shelf :exec
DELETE FROM `test_library_v1_shelf`
WHERE `id` = ?;