-- test_library_v1_shelf.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: sqlite
-- Source message: test.library.v1.Shelf
--
-- Add custom queries in queries/custom/ alongside this file.

-- name: GetTestLibraryV1Shelf :one
SELECT "id", "theme", "created_at", "updated_at"
FROM "test_library_v1_shelf"
WHERE "id" = ?
LIMIT 1;

-- name: ListTestLibraryV1Shelf :many
SELECT "id", "theme", "created_at", "updated_at"
FROM "test_library_v1_shelf"
ORDER BY "id";

-- name: CreateTestLibraryV1Shelf :one
INSERT INTO "test_library_v1_shelf" ("theme")
VALUES (?)
RETURNING *;

-- name: UpdateTestLibraryV1Shelf :one
UPDATE "test_library_v1_shelf"
SET
    "theme" = ?,
    "updated_at" = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
WHERE "id" = ?
RETURNING *;

-- name: DeleteTestLibraryV1Shelf :exec
DELETE FROM "test_library_v1_shelf"
WHERE "id" = ?;