-- test_library_v1_book.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: sqlite
-- Source message: test.library.v1.Book
--
-- Add custom queries in queries/custom/ alongside this file.

-- name: GetTestLibraryV1Book :one
SELECT "id", "shelf_id", "author", "title", "read", "created_at", "updated_at"
FROM "test_library_v1_book"
WHERE "id" = ?
LIMIT 1;

-- name: ListTestLibraryV1Book :many
SELECT "id", "shelf_id", "author", "title", "read", "created_at", "updated_at"
FROM "test_library_v1_book"
ORDER BY "id";

-- name: CreateTestLibraryV1Book :one
INSERT INTO "test_library_v1_book" ("shelf_id", "author", "title", "read")
VALUES (?, ?, ?, ?)
RETURNING *;

-- name: UpdateTestLibraryV1Book :one
UPDATE "test_library_v1_book"
SET
    "shelf_id" = ?,
    "author" = ?,
    "title" = ?,
    "read" = ?,
    "updated_at" = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
WHERE "id" = ?
RETURNING *;

-- name: DeleteTestLibraryV1Book :exec
DELETE FROM "test_library_v1_book"
WHERE "id" = ?;