import { type Expr, ExprKind } from "../common/ast/index.js";
import { type FunctionDecl, functionDecl, memberOverload, overload } from "../common/decls.js";
import type { LibrarySubset } from "../common/env/env.js";
import * as operators from "../common/operators.js";
import * as overloads from "../common/overloads.js";
import { Bool } from "../common/types/bool.js";
import { err, isError, noSuchOverloadErr } from "../common/types/err.js";
import { Int } from "../common/types/int.js";
import { Optional, OptionalNone, optionalOf } from "../common/types/optional.js";
import { DefaultTypeAdapter } from "../common/types/provider.js";
import type { Val } from "../common/types/ref/index.js";
import type { Lister, Receiver } from "../common/types/traits/index.js";
import {
  BoolType,
  DynType,
  IntType,
  listType,
  mapType,
  OptionalType,
  optionalType,
  StringType,
  TimestampType,
  type Type,
  typeParamType,
} from "../common/types/types.js";
import { isUnknown } from "../common/types/unknown.js";
import type { Activation } from "../interpreter/activation.js";
import type { ExecutionFrame } from "../interpreter/frame.js";
import {
  asFrame,
  type InterpretableCall,
  type InterpretableV2,
} from "../interpreter/interpretable.js";
import type { ExprHelper, Macro } from "../parser/options.js";
import type { EnvOptions, ProgramOptions } from "./env.js";

/**
 * Library provides a collection of environment and program options used to configure a CEL
 * environment for a particular use case or with a related set of functionality.
 *
 * The program options provided by a library are expected to be static and not vary between calls
 * to {@link Env.program}. Configure dynamic options directly within the `Env.program` call.
 */
export interface Library {
  /**
   * compileOptions contains options for configuring the parse and check environment.
   */
  readonly compileOptions: EnvOptions;

  /**
   * programOptions contains options included in every program generated by the environment.
   *
   * Library costTracking options configure the tracker. Only a costTracking option passed
   * directly to Env.program enables runtime cost tracking.
   */
  readonly programOptions: ProgramOptions;

  /**
   * requiredLibraries lists singleton libraries which must already be configured before this
   * library is applied.
   */
  readonly requiredLibraries?: readonly string[];
}

/**
 * SingletonLibrary refines Library to ensure that libraries in this format are configured only
 * once within the environment.
 */
export interface SingletonLibrary extends Library {
  /**
   * libraryName is a namespaced name used to check whether the library was already
   * configured in the environment.
   */
  readonly libraryName: string;
}

/**
 * LibraryAliaser provides a simple named alias for the library for use during environment
 * serialization.
 */
export interface LibraryAliaser {
  /**
   * libraryAlias is the simple name used to serialize the library.
   */
  readonly libraryAlias: string;
}

/**
 * LibrarySubsetter provides the subset description associated with the library, or `undefined`
 * when the library is not subset.
 */
export interface LibrarySubsetter {
  /**
   * librarySubset contains the subset description associated with the library.
   */
  readonly librarySubset: LibrarySubset | undefined;
}

/**
 * LibraryVersioner provides a version number for the library.
 *
 * If this interface is not implemented, the library version is flagged as latest during
 * environment serialization.
 */
export interface LibraryVersioner {
  /**
   * libraryVersion contains the configured library version.
   */
  readonly libraryVersion: number;
}

/**
 * LegacyTimestampOverload identifies a zero-argument timestamp receiver overload.
 */
interface LegacyTimestampOverload {
  /** functionName is the CEL timestamp function name. */
  functionName: string;
  /** overloadId is the standard timestamp overload identifier to replace. */
  overloadId: string;
}

/**
 * legacyTimestampOverloads lists the timestamp functions whose zero-argument behavior historically
 * used the source timestamp's location.
 */
const legacyTimestampOverloads: readonly LegacyTimestampOverload[] = [
  { functionName: overloads.TimeGetFullYear, overloadId: overloads.TimestampToYear },
  { functionName: overloads.TimeGetMonth, overloadId: overloads.TimestampToMonth },
  { functionName: overloads.TimeGetDayOfYear, overloadId: overloads.TimestampToDayOfYear },
  {
    functionName: overloads.TimeGetDayOfMonth,
    overloadId: overloads.TimestampToDayOfMonthZeroBased,
  },
  {
    functionName: overloads.TimeGetDate,
    overloadId: overloads.TimestampToDayOfMonthOneBased,
  },
  { functionName: overloads.TimeGetDayOfWeek, overloadId: overloads.TimestampToDayOfWeek },
  { functionName: overloads.TimeGetHours, overloadId: overloads.TimestampToHours },
  { functionName: overloads.TimeGetMinutes, overloadId: overloads.TimestampToMinutes },
  { functionName: overloads.TimeGetSeconds, overloadId: overloads.TimestampToSeconds },
  {
    functionName: overloads.TimeGetMilliseconds,
    overloadId: overloads.TimestampToMilliseconds,
  },
];

/**
 * legacyTimeFunctions returns the cel-go compatibility bindings used when default UTC behavior is
 * disabled.
 */
export function legacyTimeFunctions(): FunctionDecl[] {
  return legacyTimestampOverloads.map(({ functionName, overloadId }) =>
    functionDecl(functionName, {
      overloads: [
        memberOverload(overloadId, [TimestampType], IntType, {
          unaryBinding: (timestamp) =>
            (timestamp as unknown as Receiver).receive(functionName, overloadId, []),
        }),
      ],
    }),
  );
}

/**
 * OptionalTypesOptions configures the optional type library.
 */
export interface OptionalTypesOptions {
  /**
   * version limits the library to functions introduced at or below the selected version.
   *
   * When omitted, all available functions are included.
   */
  readonly version?: number;
}

/**
 * OptionalTypesLibrary describes the singleton optional type extension and its serialization
 * metadata.
 */
export type OptionalTypesLibrary = SingletonLibrary & LibraryAliaser & LibraryVersioner;

/**
 * optionalMapMacro performs computation on an optional value and wraps the result.
 */
const optionalMapMacro: Macro = {
  argCount: 2,
  expander: (helper, target, args) =>
    expandOptionalMap({
      args,
      flat: false,
      helper,
      target,
    }),
  function: "optMap",
  receiverStyle: true,
};

/**
 * optionalFlatMapMacro performs computation which already produces an optional result.
 */
const optionalFlatMapMacro: Macro = {
  argCount: 2,
  expander: (helper, target, args) =>
    expandOptionalMap({
      args,
      flat: true,
      helper,
      target,
    }),
  function: "optFlatMap",
  receiverStyle: true,
};

/**
 * optionalTypes enables support for optional syntax and types in CEL.
 *
 * The optional value type makes it possible to express whether variables have
 * been provided, whether a result has been computed, and in the future whether
 * an object field path, map key value, or list index has a value.
 *
 * # Syntax Changes
 *
 * Optional types are unlike other CEL extensions because they modify the CEL
 * syntax itself, notably through the use of a `?` preceding a field name or
 * index value.
 *
 * ## Field Selection
 *
 * The optional syntax in field selection is denoted as `obj.?field`. In other
 * words, if a field is set, return `optional.of(obj.field)`, else
 * `optional.none()`. The optional field selection is viral in the sense that
 * after the first optional selection all subsequent selections or indices
 * are treated as optional, so the following expressions are equivalent:
 *
 * ```cel
 * obj.?field.subfield
 * obj.?field.?subfield
 * ```
 *
 * ## Indexing
 *
 * Similar to field selection, the optional syntax can be used in index
 * expressions on maps and lists:
 *
 * ```cel
 * list[?0]
 * map[?key]
 * ```
 *
 * ## Optional Field Setting
 *
 * When creating map or message literals, if a field may be optionally set
 * based on its presence, then placing a `?` before the field name or key
 * ensures the type on the right-hand side is `optional(T)`, where `T`
 * is the type of the field or key-value.
 *
 * The following returns a map with the key expression set only if the
 * subfield is present, otherwise an empty map is created:
 *
 * ```cel
 * {?key: obj.?field.subfield}
 * ```
 *
 * ## Optional Element Setting
 *
 * When creating list literals, an element may be optionally added when the
 * element expression is preceded by a `?`:
 *
 * ```cel
 * [a, ?b, ?c]
 * ```
 *
 * The result contains `[a]`, `[a, b]`, `[a, b, c]`, or `[a, c]` depending
 * on which optional values are present.
 *
 * # Optional.Of
 *
 * Create an `optional(T)` value of a given value with type `T`.
 *
 * ```cel
 * optional.of(10)
 * ```
 *
 * # Optional.OfNonZeroValue
 *
 * Create an `optional(T)` value of a given value with type `T` if it is not a
 * zero-value. A zero-value is the default empty value for any given CEL type,
 * including empty protobuf message types. If the value is empty, the result
 * of this call is `optional.none()`.
 *
 * ```cel
 * optional.ofNonZeroValue([1, 2, 3])
 * optional.ofNonZeroValue([])
 * optional.ofNonZeroValue(0)
 * optional.ofNonZeroValue("")
 * ```
 *
 * # Optional.None
 *
 * Create an empty optional value.
 *
 * # HasValue
 *
 * Determine whether the optional contains a value.
 *
 * ```cel
 * optional.of(b'hello').hasValue()
 * optional.ofNonZeroValue({}).hasValue()
 * ```
 *
 * # Value
 *
 * Get the value contained by the optional. If the optional does not have a
 * value, the result is a CEL error.
 *
 * ```cel
 * optional.of(b'hello').value()
 * optional.ofNonZeroValue({}).value()
 * ```
 *
 * # Or
 *
 * If the value on the left-hand side is `optional.none()`, the optional value
 * on the right-hand side is returned. If the value on the left-hand side is
 * valued, then it is returned. This operation is short-circuiting and only
 * evaluates as many links in the `or` chain as needed to return a non-empty
 * optional value.
 *
 * ```cel
 * obj.?field.or(m[?key])
 * l[?index].or(obj.?field.subfield).or(obj.?other)
 * ```
 *
 * # OrValue
 *
 * Either return the value contained within the optional on the left-hand side
 * or return the alternative value on the right-hand side.
 *
 * ```cel
 * m[?key].orValue("none")
 * ```
 *
 * # OptMap
 *
 * Apply a transformation to the optional's underlying value if it is not empty
 * and return an optional typed result based on the transformation. The
 * transformation expression type must return a type `T` which is wrapped into
 * an optional.
 *
 * ```cel
 * msg.?elements.optMap(e, e.size()).orValue(0)
 * ```
 *
 * # OptFlatMap
 *
 * Introduced in version 1.
 *
 * Apply a transformation to the optional's underlying value if it is not empty
 * and return the result. The transform expression must return an `optional(T)`
 * rather than type `T`. This can be useful when dealing with zero values and
 * conditionally generating an empty or non-empty result in ways which cannot
 * be expressed with `optMap`.
 *
 * ```cel
 * msg.?elements.optFlatMap(e, e[?0])
 * ```
 *
 * # First
 *
 * Introduced in version 2. Returns an optional with the first value from the
 * right-hand list, or `optional.none()`.
 *
 * ```cel
 * [1, 2, 3].first().value() == 1
 * ```
 *
 * # Last
 *
 * Introduced in version 2. Returns an optional with the last value from the
 * right-hand list, or `optional.none()`.
 *
 * ```cel
 * [1, 2, 3].last().value() == 3
 * ```
 *
 * This is syntactic sugar for `msg.elements[msg.elements.size()-1]`.
 *
 * # Unwrap / UnwrapOpt
 *
 * Introduced in version 2. Returns a list of all values that are not empty in
 * the input list of optional values. It can be used as
 * `optional.unwrap(List[T])` or with postfix notation as `List[T].unwrapOpt()`.
 *
 * ```cel
 * optional.unwrap([optional.of(42), optional.none()]) == [42]
 * [optional.of(42), optional.none()].unwrapOpt() == [42]
 * ```
 */
export function optionalTypes(options: OptionalTypesOptions = {}): OptionalTypesLibrary {
  const version = options.version ?? 0xffffffff;
  const paramTypeK = typeParamType("K");
  const paramTypeV = typeParamType("V");
  const optionalTypeV = optionalType(paramTypeV);
  const listTypeV = listType(paramTypeV);
  const mapTypeKV = mapType(paramTypeK, paramTypeV);
  const listOptionalTypeV = listType(optionalTypeV);

  return {
    compileOptions: {
      types: [OptionalType],
      functions: [
        functionDecl("optional.of", {
          doc: "create an optional_type(T) with a value where any value is considered valid",
          overloads: [
            overload("optional_of", [paramTypeV], optionalTypeV, {
              unaryBinding: (value) => optionalOf(value),
            }),
          ],
        }),
        functionDecl("optional.ofNonZeroValue", {
          doc: "create an optional_type(T) when the value is not a zero or empty value",
          overloads: [
            overload("optional_ofNonZeroValue", [paramTypeV], optionalTypeV, {
              unaryBinding: optionalOfNonZeroValue,
            }),
          ],
        }),
        functionDecl("optional.none", {
          doc: "singleton value representing an optional without a value",
          overloads: [
            overload("optional_none", [], optionalTypeV, {
              functionBinding: () => OptionalNone,
            }),
          ],
        }),
        functionDecl("value", {
          doc: "obtain the value contained by the optional, error if optional.none()",
          overloads: [
            memberOverload("optional_value", [optionalTypeV], paramTypeV, {
              unaryBinding: (value) => (value instanceof Optional ? value.getValue() : value),
            }),
          ],
        }),
        functionDecl("hasValue", {
          doc: "determine whether the optional contains a value",
          overloads: [
            memberOverload("optional_hasValue", [optionalTypeV], BoolType, {
              unaryBinding: (value) => new Bool(value instanceof Optional && value.hasValue()),
            }),
          ],
        }),
        functionDecl("or", {
          doc: "chain optional expressions together, picking the first valued optional expression",
          overloads: [
            memberOverload("optional_or_optional", [optionalTypeV, optionalTypeV], optionalTypeV),
          ],
        }),
        functionDecl("orValue", {
          doc: "chain optional expressions together, picking the first valued optional or default",
          overloads: [
            memberOverload("optional_orValue_value", [optionalTypeV, paramTypeV], paramTypeV),
          ],
        }),
        functionDecl(operators.OptSelect, {
          doc: "create an optional field value when the field is present",
          overloads: [overload("select_optional_field", [DynType, StringType], optionalTypeV)],
        }),
        functionDecl(operators.OptIndex, {
          doc: "create an optional index value when the index is present",
          overloads: [
            overload("list_optindex_optional_int", [listTypeV, IntType], optionalTypeV),
            overload(
              "optional_list_optindex_optional_int",
              [optionalType(listTypeV), IntType],
              optionalTypeV,
            ),
            overload("map_optindex_optional_value", [mapTypeKV, paramTypeK], optionalTypeV),
            overload(
              "optional_map_optindex_optional_value",
              [optionalType(mapTypeKV), paramTypeK],
              optionalTypeV,
            ),
          ],
        }),
        functionDecl(operators.Index, {
          overloads: [
            overload("optional_list_index_int", [optionalType(listTypeV), IntType], optionalTypeV),
            overload(
              "optional_map_index_value",
              [optionalType(mapTypeKV), paramTypeK],
              optionalTypeV,
            ),
          ],
        }),
        ...(version >= 2
          ? optionalVersionTwoFunctions({
              listOptionalTypeV,
              listTypeV,
              optionalTypeV,
              paramTypeV,
            })
          : []),
      ],
      parser: {
        enableOptionalSyntax: true,
      },
      macros: {
        custom: [optionalMapMacro, ...(version >= 1 ? [optionalFlatMapMacro] : [])],
      },
    },
    libraryAlias: "optional",
    libraryName: "cel.lib.optional",
    libraryVersion: version,
    programOptions: {
      decorators: [decorateOptionalOr],
    },
  };
}

/**
 * OptionalVersionTwoFunctionOptions supplies parameterized types to version-two declarations.
 */
interface OptionalVersionTwoFunctionOptions {
  /** ListOptionalTypeV is the list of optional values accepted by unwrap functions. */
  listOptionalTypeV: Type;
  /** ListTypeV is the list type returned by unwrap and received by element helpers. */
  listTypeV: Type;
  /** OptionalTypeV is the optional result returned by element helpers. */
  optionalTypeV: Type;
  /** ParamTypeV is the generic value type contained by the optional. */
  paramTypeV: Type;
}

/**
 * optionalVersionTwoFunctions returns declarations introduced in optional library version two.
 */
function optionalVersionTwoFunctions(options: OptionalVersionTwoFunctionOptions): FunctionDecl[] {
  return [
    functionDecl("last", {
      doc: "return the last value in a list if present, otherwise optional.none()",
      overloads: [
        memberOverload("list_last", [options.listTypeV], options.optionalTypeV, {
          unaryBinding: optionalListLast,
        }),
      ],
    }),
    functionDecl("first", {
      doc: "return the first value in a list if present, otherwise optional.none()",
      overloads: [
        memberOverload("list_first", [options.listTypeV], options.optionalTypeV, {
          unaryBinding: optionalListFirst,
        }),
      ],
    }),
    functionDecl("optional.unwrap", {
      doc: "convert a list of optional values to a list containing only present values",
      overloads: [
        overload("optional_unwrap", [options.listOptionalTypeV], options.listTypeV, {
          unaryBinding: optionalUnwrap,
        }),
      ],
    }),
    functionDecl("unwrapOpt", {
      doc: "convert a list of optional values to a list containing only present values",
      overloads: [
        memberOverload("optional_unwrapOpt", [options.listOptionalTypeV], options.listTypeV, {
          unaryBinding: optionalUnwrap,
        }),
      ],
    }),
  ];
}

/**
 * optionalListFirst returns the first list value as an optional.
 */
function optionalListFirst(value: Val): Val {
  return optionalListElement({ fromEnd: false, value });
}

/**
 * optionalListLast returns the last list value as an optional.
 */
function optionalListLast(value: Val): Val {
  return optionalListElement({ fromEnd: true, value });
}

/**
 * OptionalListElementOptions selects an element from a CEL list.
 */
interface OptionalListElementOptions {
  /** FromEnd selects the final element rather than the first. */
  fromEnd: boolean;
  /** Value contains the CEL list being inspected. */
  value: Val;
}

/**
 * optionalListElement returns an empty optional for empty lists and wraps the selected element.
 */
function optionalListElement(options: OptionalListElementOptions): Val {
  if (!isLister(options.value)) {
    return noSuchOverloadErr();
  }
  const size = options.value.size();
  if (!(size instanceof Int) || size.value() === 0n) {
    return size instanceof Int ? OptionalNone : noSuchOverloadErr();
  }
  const index = options.fromEnd ? size.value() - 1n : 0n;
  return optionalOf(options.value.get(new Int(index)));
}

/**
 * optionalUnwrap filters empty optional values from a list.
 */
function optionalUnwrap(value: Val): Val {
  if (!isLister(value)) {
    return noSuchOverloadErr();
  }
  const unwrapped: Val[] = [];
  const iterator = value.iterator();
  while ((iterator.hasNext() as Bool).value()) {
    const element = iterator.next();
    if (!(element instanceof Optional)) {
      return err(`value ${String(element.value())} is not optional`);
    }
    if (element.hasValue()) {
      unwrapped.push(element.getValue());
    }
  }
  return DefaultTypeAdapter.nativeToValue(unwrapped);
}

/**
 * isLister reports whether a CEL value provides the list operations used by optional helpers.
 */
function isLister(value: Val): value is Lister {
  return (
    "size" in (value as object) &&
    typeof (value as { size?: unknown }).size === "function" &&
    "get" in (value as object) &&
    typeof (value as { get?: unknown }).get === "function" &&
    "iterator" in (value as object) &&
    typeof (value as { iterator?: unknown }).iterator === "function"
  );
}

/**
 * ExpandOptionalMapOptions supplies the macro call components used by optional map expansion.
 */
interface ExpandOptionalMapOptions {
  /** Args contains the iteration variable and mapping expression. */
  args: Expr[];
  /** Flat indicates whether the mapping expression already returns an optional. */
  flat: boolean;
  /** Helper creates parser-owned expressions with consistent identifiers. */
  helper: ExprHelper;
  /** Target contains the optional receiver expression. */
  target: Expr | undefined;
}

/**
 * expandOptionalMap converts optMap and optFlatMap calls into conditional comprehensions.
 */
function expandOptionalMap(options: ExpandOptionalMapOptions): Expr | Error {
  const variable = options.args[0];
  if (variable?.kind() !== ExprKind.Ident) {
    return options.helper.error(
      variable?.id() ?? 0,
      `${options.flat ? "optFlatMap" : "optMap"}() variable name must be a simple identifier`,
    );
  }
  if (!options.target) {
    return options.helper.error(
      variable.id(),
      `${options.flat ? "optFlatMap" : "optMap"}() missing macro target`,
    );
  }
  const variableName = variable.asIdent()!;
  const mapped = options.args[1]!;
  const value = options.helper.comprehension(
    options.helper.list(),
    "#unused",
    variableName,
    options.helper.memberCall("value", options.helper.copy(options.target)),
    options.helper.literal(false),
    options.helper.ident(variableName),
    mapped,
  );

  return options.helper.call(
    operators.Conditional,
    options.helper.memberCall("hasValue", options.target),
    options.flat ? value : options.helper.call("optional.of", value),
    options.helper.call("optional.none"),
  );
}

/**
 * optionalOfNonZeroValue wraps values that do not implement zero testing or are not zero.
 */
function optionalOfNonZeroValue(value: Val): Optional {
  if (
    !("isZeroValue" in (value as object)) ||
    typeof (value as { isZeroValue?: unknown }).isZeroValue !== "function" ||
    !(value as unknown as { isZeroValue(): boolean }).isZeroValue()
  ) {
    return optionalOf(value);
  }
  return OptionalNone;
}

/**
 * decorateOptionalOr replaces optional choice calls with short-circuiting evaluation nodes.
 */
function decorateOptionalOr(value: InterpretableV2): InterpretableV2 {
  if (
    !("functionName" in value) ||
    typeof (value as { functionName?: unknown }).functionName !== "function"
  ) {
    return value;
  }
  const call = value as InterpretableCall;
  const args = call.args();
  if (args.length !== 2) {
    return value;
  }
  switch (call.functionName()) {
    case "or":
      if (call.overloadId() !== "" && call.overloadId() !== "optional_or_optional") {
        return value;
      }
      return new OptionalOrInterpretable(call.id(), args[0]!, args[1]!);
    case "orValue":
      if (call.overloadId() !== "" && call.overloadId() !== "optional_orValue_value") {
        return value;
      }
      return new OptionalOrValueInterpretable(call.id(), args[0]!, args[1]!);
    default:
      return value;
  }
}

/**
 * OptionalOrInterpretable selects the first optional when present and otherwise evaluates the
 * second optional expression.
 */
class OptionalOrInterpretable implements InterpretableV2 {
  /**
   * constructor stores the expression id and lazy optional branches.
   */
  constructor(
    private readonly idValue: number,
    private readonly lhsValue: InterpretableV2,
    private readonly rhsValue: InterpretableV2,
  ) {}

  /**
   * id returns the expression id associated with the optional choice.
   */
  public id(): number {
    return this.idValue;
  }

  /**
   * exec evaluates the left optional and evaluates the right expression only when empty.
   */
  public exec(frame: ExecutionFrame): Val {
    // Short-circuit the right branch when the left optional already has a value.
    const lhs = this.lhsValue.exec(frame);
    if (isError(lhs) || isUnknown(lhs)) {
      return lhs;
    }
    if (!(lhs instanceof Optional)) {
      return noSuchOverloadErr();
    }
    return lhs.hasValue() ? lhs : this.rhsValue.exec(frame);
  }

  /**
   * eval evaluates the optional choice against an activation.
   */
  public eval(activation: Activation): Val {
    return this.exec(asFrame({ activation }));
  }
}

/**
 * OptionalOrValueInterpretable selects the contained value when present and otherwise evaluates
 * the concrete fallback expression.
 */
class OptionalOrValueInterpretable implements InterpretableV2 {
  /**
   * constructor stores the expression id, optional branch, and lazy fallback.
   */
  constructor(
    private readonly idValue: number,
    private readonly lhsValue: InterpretableV2,
    private readonly rhsValue: InterpretableV2,
  ) {}

  /**
   * id returns the expression id associated with the optional fallback.
   */
  public id(): number {
    return this.idValue;
  }

  /**
   * exec unwraps a present optional and evaluates the fallback only when empty.
   */
  public exec(frame: ExecutionFrame): Val {
    // Short-circuit the fallback when the left optional already has a value.
    const lhs = this.lhsValue.exec(frame);
    if (isError(lhs) || isUnknown(lhs)) {
      return lhs;
    }
    if (!(lhs instanceof Optional)) {
      return noSuchOverloadErr();
    }
    return lhs.hasValue() ? lhs.getValue() : this.rhsValue.exec(frame);
  }

  /**
   * eval evaluates the optional fallback against an activation.
   */
  public eval(activation: Activation): Val {
    return this.exec(asFrame({ activation }));
  }
}
