// src/generators/queries.ts
//
// Generates CRUD query files for each opted-in message.
// One file per message: queries/generated/{table_name}.sql
//
// SELECT queries use explicit column lists (never SELECT *) so that:
//   - Columns with skip_queries: [QUERY_TYPE_GET] or [QUERY_TYPE_LIST] are excluded
//   - Tools like sqlc can reliably infer return types from the query
//   - Column order in result sets is deterministic

import { type DescMessage, getOption } from "@bufbuild/protobuf";
import type { Schema } from "@bufbuild/protoplugin";
import {
  field as fieldOption,
  message as messageOption,
  OneofStrategy,
  oneof as oneofOption,
  QueryType,
  TimestampBehavior,
} from "../gen/protoutil/sql/v1/options_pb.js";
import { defaultColumnName, defaultTableName, toPascalCase } from "../util/naming.js";
import type { PluginOptions } from "../util/plugin-options.js";
import { pluginOneofStrategy } from "./schema.js";

export function generateQueries(schema: Schema, opts: PluginOptions): void {
  for (const file of schema.files) {
    for (const message of file.messages) {
      const msgOpts = getOption(message, messageOption);
      if (!msgOpts.generate) continue;
      const omit = new Set(msgOpts.skipQueries);
      if (omit.has(QueryType.ALL)) continue;
      generateMessageQueries(schema, message, opts, omit);
    }
  }
}

function generateMessageQueries(
  schema: Schema,
  message: DescMessage,
  opts: PluginOptions,
  omit: Set<QueryType>,
): void {
  const msgOpts = getOption(message, messageOption);
  const tableName = msgOpts.tableName || defaultTableName(message);
  const pascal = toPascalCase(tableName);
  const f = schema.generateFile(`queries/generated/${tableName}.sql`);

  f.print(`-- ${tableName}.sql`);
  f.print(`-- Generated by protoc-gen-sql. DO NOT EDIT.`);
  f.print(`-- Engine: ${opts.engine}`);
  f.print(`-- Source message: ${message.typeName}`);
  f.print(`--`);
  f.print(`-- Add custom queries in queries/custom/ alongside this file.`);
  f.print(``);

  if (!omit.has(QueryType.GET)) {
    emitGet(f, message, tableName, pascal, opts);
    f.print(``);
  }
  if (!omit.has(QueryType.LIST)) {
    emitList(f, message, tableName, pascal, opts);
    f.print(``);
  }
  if (!omit.has(QueryType.CREATE)) {
    emitCreate(f, message, tableName, pascal, opts);
    f.print(``);
  }
  if (!omit.has(QueryType.UPDATE)) {
    emitUpdate(f, message, tableName, pascal, opts);
    f.print(``);
  }
  if (!omit.has(QueryType.DELETE)) {
    emitDelete(f, tableName, pascal, opts);
  }
}

// ---------------------------------------------------------------------------
// Identifier quoting — mirrors schema.ts
// ---------------------------------------------------------------------------

function q(name: string, opts: PluginOptions): string {
  return opts.engine === "mysql" ? `\`${name}\`` : `"${name}"`;
}

// ---------------------------------------------------------------------------
// Query emitters
// ---------------------------------------------------------------------------

function emitGet(
  f: ReturnType<Schema["generateFile"]>,
  message: DescMessage,
  tableName: string,
  pascal: string,
  opts: PluginOptions,
): void {
  const cols = buildSelectColumns(message, opts, QueryType.GET)
    .map((c) => q(c, opts))
    .join(", ");

  f.print(`-- name: Get${pascal} :one`);
  if (opts.engine === "sqlserver") {
    f.print(`SELECT TOP 1 ${cols}`);
    f.print(`FROM ${q(tableName, opts)}`);
    f.print(`WHERE ${q("id", opts)} = ${param(opts, 1)};`);
  } else {
    f.print(`SELECT ${cols}`);
    f.print(`FROM ${q(tableName, opts)}`);
    f.print(`WHERE ${q("id", opts)} = ${param(opts, 1)}`);
    f.print(`LIMIT 1;`);
  }
}

function emitList(
  f: ReturnType<Schema["generateFile"]>,
  message: DescMessage,
  tableName: string,
  pascal: string,
  opts: PluginOptions,
): void {
  const cols = buildSelectColumns(message, opts, QueryType.LIST)
    .map((c) => q(c, opts))
    .join(", ");

  f.print(`-- name: List${pascal} :many`);
  f.print(`SELECT ${cols}`);
  f.print(`FROM ${q(tableName, opts)}`);
  f.print(`ORDER BY ${q("id", opts)};`);
}

function emitCreate(
  f: ReturnType<Schema["generateFile"]>,
  message: DescMessage,
  tableName: string,
  pascal: string,
  opts: PluginOptions,
): void {
  const allColumns = buildWriteColumns(message, opts, QueryType.CREATE);

  if (allColumns.length === 0) {
    f.print(`-- Create${pascal} skipped: no insertable fields`);
    return;
  }

  const cols = allColumns.map((c) => q(c, opts)).join(", ");
  const params = allColumns.map((_, i) => param(opts, i + 1)).join(", ");

  if (supportsReturning(opts)) {
    f.print(`-- name: Create${pascal} :one`);
    f.print(`INSERT INTO ${q(tableName, opts)} (${cols})`);
    f.print(`VALUES (${params})`);
    f.print(`RETURNING *;`);
  } else {
    f.print(`-- name: Create${pascal} :execresult`);
    f.print(`INSERT INTO ${q(tableName, opts)} (${cols})`);
    f.print(`VALUES (${params});`);
    f.print(``);
    f.print(`-- name: Get${pascal}ByLastInsert :one`);
    if (opts.engine === "sqlserver") {
      f.print(
        `SELECT TOP 1 * FROM ${q(tableName, opts)} WHERE ${q("id", opts)} = ${lastInsertId(opts)};`,
      );
    } else {
      // mysql only reaches here; sqlite uses RETURNING
      f.print(`SELECT * FROM ${q(tableName, opts)} WHERE ${q("id", opts)} = ${lastInsertId(opts)}`);
      f.print(`LIMIT 1;`);
    }
  }
}

function emitUpdate(
  f: ReturnType<Schema["generateFile"]>,
  message: DescMessage,
  tableName: string,
  pascal: string,
  opts: PluginOptions,
): void {
  const msgOpts = getOption(message, messageOption);
  const setColumns = buildWriteColumns(message, opts, QueryType.UPDATE);

  if (setColumns.length === 0) {
    f.print(`-- Update${pascal} skipped: no updatable fields`);
    return;
  }

  const tsb = msgOpts.timestamps;
  const hasUpdatedAt =
    tsb === TimestampBehavior.UNSPECIFIED ||
    tsb === TimestampBehavior.BOTH ||
    tsb === TimestampBehavior.UPDATED_ONLY;

  const setClauses = setColumns
    .map((col, i) => `${q(col, opts)} = ${param(opts, i + 1)}`)
    .join(",\n    ");
  const idParam = param(opts, setColumns.length + 1);

  if (supportsReturning(opts)) {
    f.print(`-- name: Update${pascal} :one`);
  } else {
    f.print(`-- name: Update${pascal} :exec`);
  }

  f.print(`UPDATE ${q(tableName, opts)}`);
  f.print(`SET`);

  if (hasUpdatedAt) {
    f.print(`    ${setClauses},`);
    f.print(`    ${q("updated_at", opts)} = ${updatedAtExpression(opts)}`);
  } else {
    f.print(`    ${setClauses}`);
  }

  f.print(`WHERE ${q("id", opts)} = ${idParam}${supportsReturning(opts) ? "\nRETURNING *;" : ";"}`);
}

function emitDelete(
  f: ReturnType<Schema["generateFile"]>,
  tableName: string,
  pascal: string,
  opts: PluginOptions,
): void {
  f.print(`-- name: Delete${pascal} :exec`);
  f.print(`DELETE FROM ${q(tableName, opts)}`);
  f.print(`WHERE ${q("id", opts)} = ${param(opts, 1)};`);
}

// ---------------------------------------------------------------------------
// Column list builders
// ---------------------------------------------------------------------------

/**
 * Builds the SELECT column list for GET and LIST queries.
 *
 * Column order mirrors the schema: id, FK columns, proto fields, oneof
 * columns, extra columns, then injected timestamp columns.
 *
 * Injected columns (id, created_at, updated_at) are only included when they
 * are actually present in the schema — id is always present, timestamps depend
 * on TimestampBehavior. They are never suppressible via skip_queries.
 *
 * All other columns are excluded if queryType is in their skip_queries list.
 */
function buildSelectColumns(
  message: DescMessage,
  opts: PluginOptions,
  queryType: QueryType.GET | QueryType.LIST,
): string[] {
  const msgOpts = getOption(message, messageOption);
  const cols: string[] = [];

  // id is always first and always present
  cols.push("id");

  // FK columns
  for (const fk of msgOpts.foreignKeys) {
    if (fk.skipQueries.includes(queryType)) continue;
    cols.push(fk.column);
  }

  // Proto fields (non-oneof, non-omitted)
  for (const field of message.fields) {
    if (field.oneof) continue;
    const fOpts = getOption(field, fieldOption);
    if (fOpts.omit) continue;
    if (fOpts.skipQueries.includes(queryType)) continue;
    cols.push(fOpts.columnName || defaultColumnName(field));
  }

  // Oneof groups
  cols.push(...collectOneofColumns(message, opts, queryType));

  // Extra columns
  for (const col of msgOpts.extraColumns) {
    if (col.skipQueries.includes(queryType)) continue;
    cols.push(col.columnName);
  }

  // Injected timestamp columns — only if active for this message
  const tsb = msgOpts.timestamps;
  if (
    tsb === TimestampBehavior.UNSPECIFIED ||
    tsb === TimestampBehavior.BOTH ||
    tsb === TimestampBehavior.CREATED_ONLY
  ) {
    cols.push("created_at");
  }
  if (
    tsb === TimestampBehavior.UNSPECIFIED ||
    tsb === TimestampBehavior.BOTH ||
    tsb === TimestampBehavior.UPDATED_ONLY
  ) {
    cols.push("updated_at");
  }

  return cols;
}

/**
 * Builds column lists for INSERT (CREATE) and UPDATE queries.
 *
 * A column is excluded if queryType is in its skip_queries list.
 * Injected columns (id, created_at, updated_at) are never included — they are
 * managed by the database.
 */
function buildWriteColumns(
  message: DescMessage,
  opts: PluginOptions,
  queryType: QueryType.CREATE | QueryType.UPDATE,
): string[] {
  const msgOpts = getOption(message, messageOption);
  const cols: string[] = [];

  // FK columns
  for (const fk of msgOpts.foreignKeys) {
    if (fk.skipQueries.includes(queryType)) continue;
    cols.push(fk.column);
  }

  // Proto fields (non-oneof, non-omitted)
  for (const field of message.fields) {
    if (field.oneof) continue;
    const fOpts = getOption(field, fieldOption);
    if (fOpts.omit) continue;
    if (fOpts.skipQueries.includes(queryType)) continue;
    cols.push(fOpts.columnName || defaultColumnName(field));
  }

  // Oneof groups
  cols.push(...collectOneofColumns(message, opts, queryType));

  // Extra columns
  for (const col of msgOpts.extraColumns) {
    if (col.skipQueries.includes(queryType)) continue;
    cols.push(col.columnName);
  }

  return cols;
}

/**
 * Returns the column names that oneof groups contribute to a query.
 * Mirrors the schema emitter's oneof handling:
 *   NULLABLE_COLS  → one column per variant field
 *   TYPE_COLUMN    → two synthetic columns: {name}_type, {name}_value
 *   JSON_COLUMN    → one synthetic column: {name}
 *
 * A oneof is excluded entirely if queryType is in its skip_queries list.
 */
function collectOneofColumns(
  message: DescMessage,
  opts: PluginOptions,
  queryType: QueryType,
): string[] {
  const cols: string[] = [];
  const oneofsSeen = new Set<string>();

  for (const field of message.fields) {
    if (!field.oneof) continue;
    if (oneofsSeen.has(field.oneof.name)) continue;
    oneofsSeen.add(field.oneof.name);

    const oneofOpts = getOption(field.oneof, oneofOption);
    if (oneofOpts.skipQueries.includes(queryType)) continue;

    const strategy =
      oneofOpts.strategy !== OneofStrategy.UNSPECIFIED
        ? oneofOpts.strategy
        : pluginOneofStrategy(opts);

    const fields = message.fields.filter((f) => f.oneof?.name === field.oneof!.name);

    switch (strategy) {
      case OneofStrategy.NULLABLE_COLS:
        for (const f of fields) {
          cols.push(defaultColumnName(f));
        }
        break;
      case OneofStrategy.TYPE_COLUMN:
        cols.push(`${field.oneof.name}_type`);
        cols.push(`${field.oneof.name}_value`);
        break;
      case OneofStrategy.JSON_COLUMN:
        cols.push(field.oneof.name);
        break;
    }
  }

  return cols;
}

// ---------------------------------------------------------------------------
// Engine helpers
// ---------------------------------------------------------------------------

function param(opts: PluginOptions, index: number): string {
  switch (opts.engine) {
    case "postgres":
      return `$${index}`;
    case "mysql":
    case "sqlite":
      return `?`;
    case "sqlserver":
      return `@p${index}`;
  }
}

function supportsReturning(opts: PluginOptions): boolean {
  return opts.engine === "postgres" || opts.engine === "sqlite";
}

function lastInsertId(opts: PluginOptions): string {
  switch (opts.engine) {
    case "mysql":
      return "LAST_INSERT_ID()";
    case "sqlserver":
      return "SCOPE_IDENTITY()";
    default:
      // postgres and sqlite use RETURNING; this branch is unreachable for them
      return "";
  }
}

function updatedAtExpression(opts: PluginOptions): string {
  switch (opts.engine) {
    case "postgres":
      return "now()";
    case "mysql":
      return "CURRENT_TIMESTAMP(6)";
    case "sqlite":
      return "(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))";
    case "sqlserver":
      return "SYSDATETIMEOFFSET()";
  }
}
