import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { generate, LIBRARY_PROTO } from "../test-helpers.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixture = (path: string) =>
  readFileSync(resolve(__dirname, "../fixtures", path), "utf8").trim();

interface QueryCase {
  description: string;
  proto: string;
  engine: string;
  file: string;
  expectedContent: string; // full file content — no partial matching
}

// ---------------------------------------------------------------------------
// Helper: standard header for generated query files
// ---------------------------------------------------------------------------
const header = (tableName: string, engine: string, typeName: string) => `\
-- ${tableName}.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: ${engine}
-- Source message: ${typeName}
--
-- Add custom queries in queries/custom/ alongside this file.`;

// ---------------------------------------------------------------------------
// QUERY_CASES — full-file data-driven tests
// ---------------------------------------------------------------------------
const QUERY_CASES: QueryCase[] = [
  // -------------------------------------------------------------------------
  // Full CRUD — each engine's syntax
  // -------------------------------------------------------------------------
  {
    description: "postgres: full CRUD file for a simple message",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title  = 1;
        string author = 2;
        bool   read   = 3;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "author", "read", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "author", "read", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title", "author", "read")
VALUES ($1, $2, $3)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "author" = $2,
    "read" = $3,
    "updated_at" = now()
WHERE "id" = $4
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "mysql: full CRUD uses ? params, :execresult create, :exec update, LAST_INSERT_ID",
    engine: "mysql",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title  = 1;
        string author = 2;
      }
    `,
    expectedContent: `
${header("test_v1_book", "mysql", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT \`id\`, \`title\`, \`author\`, \`created_at\`, \`updated_at\`
FROM \`test_v1_book\`
WHERE \`id\` = ?
LIMIT 1;

-- name: ListTestV1Book :many
SELECT \`id\`, \`title\`, \`author\`, \`created_at\`, \`updated_at\`
FROM \`test_v1_book\`
ORDER BY \`id\`;

-- name: CreateTestV1Book :execresult
INSERT INTO \`test_v1_book\` (\`title\`, \`author\`)
VALUES (?, ?);

-- name: GetTestV1BookByLastInsert :one
SELECT * FROM \`test_v1_book\` WHERE \`id\` = LAST_INSERT_ID()
LIMIT 1;

-- name: UpdateTestV1Book :exec
UPDATE \`test_v1_book\`
SET
    \`title\` = ?,
    \`author\` = ?,
    \`updated_at\` = CURRENT_TIMESTAMP(6)
WHERE \`id\` = ?;

-- name: DeleteTestV1Book :exec
DELETE FROM \`test_v1_book\`
WHERE \`id\` = ?;
    `.trim(),
  },
  {
    description: "sqlserver: uses @p1 style params and SELECT TOP 1 instead of LIMIT",
    engine: "sqlserver",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "sqlserver", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT TOP 1 "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = @p1;

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :execresult
INSERT INTO "test_v1_book" ("title")
VALUES (@p1);

-- name: GetTestV1BookByLastInsert :one
SELECT TOP 1 * FROM "test_v1_book" WHERE "id" = SCOPE_IDENTITY();

-- name: UpdateTestV1Book :exec
UPDATE "test_v1_book"
SET
    "title" = @p1,
    "updated_at" = SYSDATETIMEOFFSET()
WHERE "id" = @p2;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = @p1;
    `.trim(),
  },
  {
    description: "sqlite: uses ? params and RETURNING",
    engine: "sqlite",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "sqlite", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = ?
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES (?)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = ?,
    "updated_at" = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
WHERE "id" = ?
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = ?;
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // skip_queries — individual message-level query suppression
  // -------------------------------------------------------------------------
  {
    description: "QUERY_TYPE_GET suppresses only the Get query",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, skip_queries: [QUERY_TYPE_GET] };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "QUERY_TYPE_LIST suppresses only the List query",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, skip_queries: [QUERY_TYPE_LIST] };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "QUERY_TYPE_CREATE suppresses only the Create query",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, skip_queries: [QUERY_TYPE_CREATE] };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "QUERY_TYPE_UPDATE suppresses only the Update query",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, skip_queries: [QUERY_TYPE_UPDATE] };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "QUERY_TYPE_DELETE suppresses only the Delete query",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, skip_queries: [QUERY_TYPE_DELETE] };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // omit — fields excluded from INSERT/UPDATE but still in SELECT
  // -------------------------------------------------------------------------
  {
    description: "omitted fields excluded from INSERT and UPDATE but still appear in SELECT",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string name  = 1 [(protoutil.sql.v1.field).omit = true];
        string title = 2;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // FK columns — in SELECT, INSERT, and UPDATE
  // -------------------------------------------------------------------------
  {
    description: "FK column included in SELECT, INSERT, and UPDATE",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf" }]
        };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "shelf_id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "shelf_id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("shelf_id", "title")
VALUES ($1, $2)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "shelf_id" = $1,
    "title" = $2,
    "updated_at" = now()
WHERE "id" = $3
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "multiple FKs: all FK columns in SELECT, INSERT, and UPDATE in declaration order",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [
            { column: "author_id", references_table: "test_v1_author" },
            { column: "shelf_id",  references_table: "test_v1_shelf" }
          ]
        };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "author_id", "shelf_id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "author_id", "shelf_id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("author_id", "shelf_id", "title")
VALUES ($1, $2, $3)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "author_id" = $1,
    "shelf_id" = $2,
    "title" = $3,
    "updated_at" = now()
WHERE "id" = $4
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // TimestampBehavior — SELECT column list respects active timestamps
  // -------------------------------------------------------------------------
  {
    description: "TIMESTAMP_BEHAVIOR_CREATED_ONLY: SELECT includes created_at but not updated_at",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          timestamps: TIMESTAMP_BEHAVIOR_CREATED_ONLY
        };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "created_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "TIMESTAMP_BEHAVIOR_UPDATED_ONLY: SELECT includes updated_at but not created_at",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          timestamps: TIMESTAMP_BEHAVIOR_UPDATED_ONLY
        };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "TIMESTAMP_BEHAVIOR_NONE: SELECT excludes both timestamp columns",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          timestamps: TIMESTAMP_BEHAVIOR_NONE
        };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // skip_queries on proto fields
  // -------------------------------------------------------------------------
  {
    description: "field skip_queries [GET, LIST]: excluded from SELECT but still in writes",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title         = 1;
        string password_hash = 2 [(protoutil.sql.v1.field).skip_queries = QUERY_TYPE_GET, (protoutil.sql.v1.field).skip_queries = QUERY_TYPE_LIST];
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title", "password_hash")
VALUES ($1, $2)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "password_hash" = $2,
    "updated_at" = now()
WHERE "id" = $3
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "field skip_queries [CREATE, UPDATE]: excluded from writes but still in SELECT",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title      = 1;
        string search_vec = 2 [(protoutil.sql.v1.field).skip_queries = QUERY_TYPE_CREATE, (protoutil.sql.v1.field).skip_queries = QUERY_TYPE_UPDATE];
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "search_vec", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "search_vec", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // skip_queries on FK columns
  // -------------------------------------------------------------------------
  {
    description: "FK skip_queries [UPDATE]: excluded from UPDATE SET but in SELECT and INSERT",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{
            column: "shelf_id"
            references_table: "test_v1_shelf"
            skip_queries: [QUERY_TYPE_UPDATE]
          }]
        };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "shelf_id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "shelf_id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("shelf_id", "title")
VALUES ($1, $2)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "FK skip_queries [GET, LIST]: excluded from SELECT but in INSERT and UPDATE",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{
            column: "shard_key"
            references_table: "test_v1_shard"
            skip_queries: [QUERY_TYPE_GET, QUERY_TYPE_LIST]
          }]
        };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("shard_key", "title")
VALUES ($1, $2)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "shard_key" = $1,
    "title" = $2,
    "updated_at" = now()
WHERE "id" = $3
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // skip_queries on extra_columns
  // -------------------------------------------------------------------------
  {
    description: "extra_column without skip_queries: included in SELECT, INSERT, and UPDATE",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          extra_columns: [{ column_name: "tenant_id", column_type: "BIGINT" }]
        };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "tenant_id", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "tenant_id", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title", "tenant_id")
VALUES ($1, $2)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "tenant_id" = $2,
    "updated_at" = now()
WHERE "id" = $3
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "extra_column skip_queries [CREATE, UPDATE]: in SELECT but excluded from writes",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          extra_columns: [{
            column_name: "row_version"
            column_type: "BIGINT"
            default: "1"
            skip_queries: [QUERY_TYPE_CREATE, QUERY_TYPE_UPDATE]
          }]
        };
        string title = 1;
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "row_version", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "row_version", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // skip_queries on oneof groups
  // -------------------------------------------------------------------------
  {
    description: "oneof NULLABLE_COLS: columns included in SELECT, INSERT, and UPDATE by default",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title = 1;
        oneof contact {
          string email = 2;
          string phone = 3;
        }
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "email", "phone", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "email", "phone", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title", "email", "phone")
VALUES ($1, $2, $3)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "email" = $2,
    "phone" = $3,
    "updated_at" = now()
WHERE "id" = $4
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "oneof TYPE_COLUMN: synthetic columns included in SELECT, INSERT, and UPDATE",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title = 1;
        oneof contact {
          option (protoutil.sql.v1.oneof).strategy = ONEOF_STRATEGY_TYPE_COLUMN;
          string email = 2;
          string phone = 3;
        }
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "contact_type", "contact_value", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "contact_type", "contact_value", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title", "contact_type", "contact_value")
VALUES ($1, $2, $3)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "contact_type" = $2,
    "contact_value" = $3,
    "updated_at" = now()
WHERE "id" = $4
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description:
      "oneof JSON_COLUMN: single synthetic column included in SELECT, INSERT, and UPDATE",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title = 1;
        oneof contact {
          option (protoutil.sql.v1.oneof).strategy = ONEOF_STRATEGY_JSON_COLUMN;
          string email = 2;
          string phone = 3;
        }
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "contact", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "contact", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title", "contact")
VALUES ($1, $2)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "contact" = $2,
    "updated_at" = now()
WHERE "id" = $3
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
  {
    description: "oneof skip_queries [CREATE, UPDATE, GET, LIST]: excluded from all queries",
    engine: "postgres",
    file: "queries/generated/test_v1_book.sql",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title = 1;
        oneof contact {
          option (protoutil.sql.v1.oneof).skip_queries = QUERY_TYPE_CREATE;
          option (protoutil.sql.v1.oneof).skip_queries = QUERY_TYPE_UPDATE;
          option (protoutil.sql.v1.oneof).skip_queries = QUERY_TYPE_GET;
          option (protoutil.sql.v1.oneof).skip_queries = QUERY_TYPE_LIST;
          string email = 2;
          string phone = 3;
        }
      }
    `,
    expectedContent: `
${header("test_v1_book", "postgres", "test.v1.Book")}

-- name: GetTestV1Book :one
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
WHERE "id" = $1
LIMIT 1;

-- name: ListTestV1Book :many
SELECT "id", "title", "created_at", "updated_at"
FROM "test_v1_book"
ORDER BY "id";

-- name: CreateTestV1Book :one
INSERT INTO "test_v1_book" ("title")
VALUES ($1)
RETURNING *;

-- name: UpdateTestV1Book :one
UPDATE "test_v1_book"
SET
    "title" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING *;

-- name: DeleteTestV1Book :exec
DELETE FROM "test_v1_book"
WHERE "id" = $1;
    `.trim(),
  },
];

describe("query generator — unit", () => {
  for (const tc of QUERY_CASES) {
    it(tc.description, async () => {
      const files = await generate(tc.proto, { engine: tc.engine });
      expect(files.get(tc.file)?.trim()).toBe(tc.expectedContent);
    });
  }

  it("QUERY_TYPE_ALL suppresses query file but schema file is still generated", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, skip_queries: [QUERY_TYPE_ALL] };
        string title = 1;
      }
    `,
      { engine: "postgres" },
    );
    expect(files.has("queries/generated/test_v1_book.sql")).toBe(false);
    expect(files.has("schema.sql")).toBe(true);
  });

  it("does not generate query files for non-opted-in messages", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Request { string name = 1; }
    `,
      { engine: "postgres" },
    );
    for (const key of files.keys()) {
      expect(key).not.toMatch(/queries\/generated/);
    }
  });
});

describe("query generator — e2e", () => {
  const E2E_CASES = [
    { engine: "postgres", table: "shelf" },
    { engine: "postgres", table: "book" },
    { engine: "mysql", table: "shelf" },
    { engine: "mysql", table: "book" },
    { engine: "sqlite", table: "shelf" },
    { engine: "sqlite", table: "book" },
    { engine: "sqlserver", table: "shelf" },
    { engine: "sqlserver", table: "book" },
  ];

  for (const { engine, table } of E2E_CASES) {
    it(`${engine}: ${table} queries match fixture`, async () => {
      const files = await generate(LIBRARY_PROTO, { engine });
      expect(files.get(`queries/generated/test_library_v1_${table}.sql`)?.trim()).toBe(
        fixture(`${engine}/test_library_v1_${table}.sql`),
      );
    });
  }

  it("generates query files only for opted-in messages", async () => {
    const files = await generate(LIBRARY_PROTO, { engine: "postgres" });
    const queryFiles = [...files.keys()].filter((k) => k.startsWith("queries/generated/"));
    expect(queryFiles.sort()).toEqual([
      "queries/generated/test_library_v1_book.sql",
      "queries/generated/test_library_v1_shelf.sql",
    ]);
  });
});
