import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { generate, LIBRARY_PROTO } from "../test-helpers.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixture = (path: string) =>
  readFileSync(resolve(__dirname, "../fixtures", path), "utf8").trim();

interface SchemaCase {
  description: string;
  proto: string;
  engine: string;
  expectedSchema: string;
}

const SCHEMA_CASES: SchemaCase[] = [
  {
    description: "no opted-in messages produces empty schema comment",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test; import "protoutil/sql/v1/options.proto";
      message Ignored { string name = 1; }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- No messages opted into generation.
-- Add option (protoutil.sql.v1.message).generate = true to a message to generate a table.
    `.trim(),
  },
  {
    description: "postgres scalar type mapping",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Types {
        option (protoutil.sql.v1.message).generate = true;
        string f_string = 1;
        bool   f_bool   = 2;
        int32  f_int32  = 3;
        int64  f_int64  = 4;
        float  f_float  = 5;
        double f_double = 6;
        bytes  f_bytes  = 7;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Types
CREATE TABLE IF NOT EXISTS "test_v1_types" (
    "id" BIGSERIAL NOT NULL,
    "f_string" TEXT NOT NULL,
    "f_bool" BOOLEAN NOT NULL,
    "f_int32" INTEGER NOT NULL,
    "f_int64" BIGINT NOT NULL,
    "f_float" REAL NOT NULL,
    "f_double" DOUBLE PRECISION NOT NULL,
    "f_bytes" BYTEA NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "sqlite scalar type mapping",
    engine: "sqlite",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Types {
        option (protoutil.sql.v1.message).generate = true;
        string f_string = 1;
        bool   f_bool   = 2;
        int32  f_int32  = 3;
        int64  f_int64  = 4;
        float  f_float  = 5;
        double f_double = 6;
        bytes  f_bytes  = 7;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: sqlite
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Types
CREATE TABLE IF NOT EXISTS "test_v1_types" (
    "id" INTEGER NOT NULL,
    "f_string" TEXT NOT NULL,
    "f_bool" INTEGER NOT NULL,
    "f_int32" INTEGER NOT NULL,
    "f_int64" INTEGER NOT NULL,
    "f_float" REAL NOT NULL,
    "f_double" REAL NOT NULL,
    "f_bytes" BLOB NOT NULL,
    "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "table_name override replaces default name",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, table_name: "books" };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "books" (
    "id" BIGSERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "omit = true excludes field from schema",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string name  = 1 [(protoutil.sql.v1.field).omit = true];
        string title = 2;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "column_name override renames the column",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title = 1 [(protoutil.sql.v1.field).column_name = "book_title"];
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "book_title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "column_type override replaces inferred type",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string title = 1 [(protoutil.sql.v1.field).column_type = "VARCHAR(255)"];
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "type_overrides uses sqlite-specific type for bool",
    engine: "sqlite",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        bool read = 1 [(protoutil.sql.v1.field).type_overrides = { key: "sqlite" value: "INTEGER" }, (protoutil.sql.v1.field).type_overrides = { key: "postgres" value: "BOOLEAN" }];
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: sqlite
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" INTEGER NOT NULL,
    "read" INTEGER NOT NULL,
    "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "nullable = true and default emit NULL and DEFAULT clause",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string subtitle = 1 [(protoutil.sql.v1.field) = { nullable: true, default: "''" }];
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "subtitle" TEXT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "FK column, REFERENCES constraint, and FK index emitted in dependency order",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf {
        option (protoutil.sql.v1.message).generate = true;
        string theme = 1;
      }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf", on_delete: FOREIGN_KEY_ACTION_CASCADE }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" BIGSERIAL NOT NULL,
    "theme" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");
    `.trim(),
  },
  {
    description: "FieldOptions.index emits single-column index after CREATE TABLE",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        string author = 1 [(protoutil.sql.v1.field).index = true];
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "author" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_author" ON "test_v1_book" ("author");
    `.trim(),
  },
  {
    description: "MessageOptions.indexes emits composite index",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, indexes: ["author,title"] };
        string author = 1;
        string title  = 2;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "author" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_author_title" ON "test_v1_book" ("author", "title");
    `.trim(),
  },
  {
    description: "TIMESTAMP_BEHAVIOR_NONE suppresses both timestamp columns",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, timestamps: TIMESTAMP_BEHAVIOR_NONE };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "title" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "TIMESTAMP_BEHAVIOR_CREATED_ONLY suppresses updated_at",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, timestamps: TIMESTAMP_BEHAVIOR_CREATED_ONLY };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "extra_columns are injected before timestamps with correct type and nullability",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          extra_columns: [{ column_name: "deleted_at", column_type: "TIMESTAMPTZ", nullable: true }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "extra_columns type_overrides uses engine-specific type",
    engine: "sqlite",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          extra_columns: [{
            column_name: "deleted_at",
            column_type: "TIMESTAMPTZ",
            type_overrides: { key: "sqlite" value: "TEXT" },
            nullable: true
          }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: sqlite
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "deleted_at" TEXT NULL,
    "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY ("id")
);
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // ForeignKeyAction — ON DELETE / ON UPDATE clauses
  // -------------------------------------------------------------------------
  {
    description: "FK with ON DELETE CASCADE emits ON DELETE CASCADE clause",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf { option (protoutil.sql.v1.message).generate = true; string name = 1; }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf", on_delete: FOREIGN_KEY_ACTION_CASCADE }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" BIGSERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");
    `.trim(),
  },
  {
    description: "FK with ON DELETE RESTRICT emits ON DELETE RESTRICT clause",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf { option (protoutil.sql.v1.message).generate = true; string name = 1; }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf", on_delete: FOREIGN_KEY_ACTION_RESTRICT }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" BIGSERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");
    `.trim(),
  },
  {
    description: "FK with ON DELETE SET NULL emits ON DELETE SET NULL clause",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf { option (protoutil.sql.v1.message).generate = true; string name = 1; }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf", on_delete: FOREIGN_KEY_ACTION_SET_NULL }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" BIGSERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");
    `.trim(),
  },
  {
    description: "FK with ON UPDATE CASCADE emits ON UPDATE CASCADE clause",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf { option (protoutil.sql.v1.message).generate = true; string name = 1; }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf", on_update: FOREIGN_KEY_ACTION_CASCADE }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" BIGSERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id") ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");
    `.trim(),
  },
  {
    description: "FK with both ON DELETE CASCADE and ON UPDATE RESTRICT emits both clauses",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf { option (protoutil.sql.v1.message).generate = true; string name = 1; }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{
            column: "shelf_id"
            references_table: "test_v1_shelf"
            on_delete: FOREIGN_KEY_ACTION_CASCADE
            on_update: FOREIGN_KEY_ACTION_RESTRICT
          }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" BIGSERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id") ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");
    `.trim(),
  },
  {
    description: "FK with FOREIGN_KEY_ACTION_NO_ACTION emits ON DELETE NO ACTION clause",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf { option (protoutil.sql.v1.message).generate = true; string name = 1; }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf", on_delete: FOREIGN_KEY_ACTION_NO_ACTION }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" BIGSERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id") ON DELETE NO ACTION
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // Multiple FKs on a single table
  // -------------------------------------------------------------------------
  {
    description: "multiple FKs on one table emit all FK columns, constraints, and indexes",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Author { option (protoutil.sql.v1.message).generate = true; string name = 1; }
      message Shelf  { option (protoutil.sql.v1.message).generate = true; string theme = 1; }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [
            { column: "author_id", references_table: "test_v1_author" },
            { column: "shelf_id",  references_table: "test_v1_shelf", on_delete: FOREIGN_KEY_ACTION_CASCADE }
          ]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Author
CREATE TABLE IF NOT EXISTS "test_v1_author" (
    "id" BIGSERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" BIGSERIAL NOT NULL,
    "theme" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "author_id" BIGINT NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_author_id" FOREIGN KEY ("author_id") REFERENCES "test_v1_author" ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_author_id" ON "test_v1_book" ("author_id");
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");
    `.trim(),
  },

  // -------------------------------------------------------------------------
  // Circular FK references — dependency ordering
  // -------------------------------------------------------------------------
  {
    description: "circular FK references are handled without infinite loop",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Employee {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "manager_id", references_table: "test_v1_employee" }]
        };
        string name = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Employee
CREATE TABLE IF NOT EXISTS "test_v1_employee" (
    "id" BIGSERIAL NOT NULL,
    "manager_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_employee_manager_id" FOREIGN KEY ("manager_id") REFERENCES "test_v1_employee" ("id")
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_employee_manager_id" ON "test_v1_employee" ("manager_id");
    `.trim(),
  },
  {
    description:
      "mutually circular FKs between two tables are handled without infinite loop (dep visited first)",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Chicken {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "egg_id", references_table: "test_v1_egg" }]
        };
        string name = 1;
      }
      message Egg {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "chicken_id", references_table: "test_v1_chicken" }]
        };
        string colour = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Egg
CREATE TABLE IF NOT EXISTS "test_v1_egg" (
    "id" BIGSERIAL NOT NULL,
    "chicken_id" BIGINT NOT NULL,
    "colour" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_egg_chicken_id" FOREIGN KEY ("chicken_id") REFERENCES "test_v1_chicken" ("id")
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_egg_chicken_id" ON "test_v1_egg" ("chicken_id");

-- test.v1.Chicken
CREATE TABLE IF NOT EXISTS "test_v1_chicken" (
    "id" BIGSERIAL NOT NULL,
    "egg_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_chicken_egg_id" FOREIGN KEY ("egg_id") REFERENCES "test_v1_egg" ("id")
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_chicken_egg_id" ON "test_v1_chicken" ("egg_id");
    `.trim(),
  },
];

describe("schema generator — unit", () => {
  for (const tc of SCHEMA_CASES) {
    it(tc.description, async () => {
      const files = await generate(tc.proto, { engine: tc.engine });
      expect(files.get("schema.sql")?.trim()).toBe(tc.expectedSchema);
    });
  }
});

describe("schema generator — e2e", () => {
  it("postgres: full library schema matches fixture", async () => {
    const files = await generate(LIBRARY_PROTO, { engine: "postgres" });
    expect(files.get("schema.sql")?.trim()).toBe(fixture("postgres/schema.sql"));
  });

  it("sqlite: full library schema matches fixture", async () => {
    const files = await generate(LIBRARY_PROTO, { engine: "sqlite" });
    expect(files.get("schema.sql")?.trim()).toBe(fixture("sqlite/schema.sql"));
  });

  it("mysql: full library schema matches fixture", async () => {
    const files = await generate(LIBRARY_PROTO, { engine: "mysql" });
    expect(files.get("schema.sql")?.trim()).toBe(fixture("mysql/schema.sql"));
  });

  it("sqlserver: full library schema matches fixture", async () => {
    const files = await generate(LIBRARY_PROTO, { engine: "sqlserver" });
    expect(files.get("schema.sql")?.trim()).toBe(fixture("sqlserver/schema.sql"));
  });
});

describe("schema generator — IF NOT EXISTS option", () => {
  it("default (if_not_exists unset) produces IF NOT EXISTS", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book { option (protoutil.sql.v1.message).generate = true; string title = 1; }
    `,
      { engine: "postgres" },
    );
    const schema = files.get("schema.sql")!;
    expect(schema).toContain("CREATE TABLE IF NOT EXISTS");
  });

  it("if_not_exists=true explicitly produces IF NOT EXISTS", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book { option (protoutil.sql.v1.message).generate = true; string title = 1 [(protoutil.sql.v1.field).index = true]; }
    `,
      { engine: "postgres", if_not_exists: "true" },
    );
    const schema = files.get("schema.sql")!;
    expect(schema).toContain("CREATE TABLE IF NOT EXISTS");
    expect(schema).toContain("CREATE INDEX IF NOT EXISTS");
  });

  it("if_not_exists=false omits IF NOT EXISTS from CREATE TABLE", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book { option (protoutil.sql.v1.message).generate = true; string title = 1; }
    `,
      { engine: "postgres", if_not_exists: "false" },
    );
    const schema = files.get("schema.sql")!;
    expect(schema).toContain('CREATE TABLE "test_v1_book"');
    expect(schema).not.toContain("IF NOT EXISTS");
  });

  it("if_not_exists=false omits IF NOT EXISTS from all CREATE INDEX statements", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, indexes: ["author"] };
        string author = 1 [(protoutil.sql.v1.field).index = true];
      }
    `,
      { engine: "postgres", if_not_exists: "false" },
    );
    const schema = files.get("schema.sql")!;
    expect(schema).not.toContain("IF NOT EXISTS");
    expect(schema).toContain('CREATE INDEX "idx_test_v1_book_author"');
  });
});

// ---------------------------------------------------------------------------
// New feature cases — appended to SCHEMA_CASES data-driven block
// ---------------------------------------------------------------------------

const SCHEMA_NEW_CASES: SchemaCase[] = [
  {
    description: "PRIMARY_KEY_TYPE_UUID uses UUID DEFAULT gen_random_uuid() on postgres",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, primary_key: PRIMARY_KEY_TYPE_UUID };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" UUID DEFAULT gen_random_uuid() NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "PRIMARY_KEY_TYPE_UUID uses TEXT DEFAULT on sqlite",
    engine: "sqlite",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Book {
        option (protoutil.sql.v1.message) = { generate: true, primary_key: PRIMARY_KEY_TYPE_UUID };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: sqlite
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" TEXT DEFAULT (lower(hex(randomblob(16)))) NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "UUID PK causes FK columns to use UUID type",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf {
        option (protoutil.sql.v1.message) = { generate: true, primary_key: PRIMARY_KEY_TYPE_UUID };
        string theme = 1;
      }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          primary_key: PRIMARY_KEY_TYPE_UUID
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf" }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" UUID DEFAULT gen_random_uuid() NOT NULL,
    "theme" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" UUID DEFAULT gen_random_uuid() NOT NULL,
    "shelf_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id")
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");
    `.trim(),
  },
  {
    description: "ENUM_STRATEGY_NAME stores as TEXT (default)",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      enum Status { STATUS_UNSPECIFIED = 0; STATUS_ACTIVE = 1; STATUS_INACTIVE = 2; }
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        Status status = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "status" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "ENUM_STRATEGY_INT stores as INTEGER",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      enum Status { STATUS_UNSPECIFIED = 0; STATUS_ACTIVE = 1; STATUS_INACTIVE = 2; }
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        Status status = 1 [(protoutil.sql.v1.field).enum_strategy = ENUM_STRATEGY_INT];
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "status" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "ENUM_STRATEGY_CHECK_CONSTRAINT stores as TEXT with CHECK listing valid names",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      enum Status { STATUS_UNSPECIFIED = 0; STATUS_ACTIVE = 1; STATUS_INACTIVE = 2; }
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        Status status = 1 [(protoutil.sql.v1.field).enum_strategy = ENUM_STRATEGY_CHECK_CONSTRAINT];
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "status" TEXT CHECK ("status" IN ('STATUS_UNSPECIFIED', 'STATUS_ACTIVE', 'STATUS_INACTIVE')) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "check field emits inline CHECK constraint on column",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Product {
        option (protoutil.sql.v1.message).generate = true;
        int32 price_cents = 1 [(protoutil.sql.v1.field).check = "price_cents > 0"];
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Product
CREATE TABLE IF NOT EXISTS "test_v1_product" (
    "id" BIGSERIAL NOT NULL,
    "price_cents" INTEGER NOT NULL CHECK (price_cents > 0),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "check field on extra_columns emits inline CHECK constraint",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Order {
        option (protoutil.sql.v1.message) = {
          generate: true
          extra_columns: [{
            column_name: "row_version"
            column_type: "BIGINT"
            default: "1"
            check: "row_version >= 1"
          }]
        };
        string reference = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Order
CREATE TABLE IF NOT EXISTS "test_v1_order" (
    "id" BIGSERIAL NOT NULL,
    "reference" TEXT NOT NULL,
    "row_version" BIGINT NOT NULL DEFAULT 1 CHECK (row_version >= 1),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
    `.trim(),
  },
  {
    description: "FK index is emitted by default",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf { option (protoutil.sql.v1.message).generate = true; string name = 1; }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf" }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" BIGSERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id")
);
CREATE INDEX IF NOT EXISTS "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");
    `.trim(),
  },
  {
    description: "skip_index = true suppresses FK index",
    engine: "postgres",
    proto: `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf { option (protoutil.sql.v1.message).generate = true; string name = 1; }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf", skip_index: true }]
        };
        string title = 1;
      }
    `,
    expectedSchema: `
-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: postgres
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.v1.Shelf
CREATE TABLE IF NOT EXISTS "test_v1_shelf" (
    "id" BIGSERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- test.v1.Book
CREATE TABLE IF NOT EXISTS "test_v1_book" (
    "id" BIGSERIAL NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id")
);
    `.trim(),
  },
];

describe("schema generator — new features", () => {
  for (const tc of SCHEMA_NEW_CASES) {
    it(tc.description, async () => {
      const files = await generate(tc.proto, { engine: tc.engine });
      expect(files.get("schema.sql")?.trim()).toBe(tc.expectedSchema);
    });
  }
});

// ---------------------------------------------------------------------------
// MySQL backtick quoting — inline unit tests
// ---------------------------------------------------------------------------

describe("schema generator — mysql backtick quoting", () => {
  it("mysql: table with FK and index uses backtick identifiers throughout", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf {
        option (protoutil.sql.v1.message).generate = true;
        string theme = 1;
      }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf", on_delete: FOREIGN_KEY_ACTION_CASCADE }]
        };
        string title = 1 [(protoutil.sql.v1.field).index = true];
      }
    `,
      { engine: "mysql" },
    );
    const schema = files.get("schema.sql")!;

    // All identifiers must be backtick-quoted, never double-quoted
    expect(schema).not.toContain('"');

    // Table and column identifiers
    expect(schema).toContain("`test_v1_shelf`");
    expect(schema).toContain("`test_v1_book`");
    expect(schema).toContain("`shelf_id`");
    expect(schema).toContain("`title`");

    // FK constraint with backticks
    expect(schema).toContain(
      "CONSTRAINT `fk_test_v1_book_shelf_id` FOREIGN KEY (`shelf_id`) REFERENCES `test_v1_shelf` (`id`) ON DELETE CASCADE",
    );

    // Index with backticks
    expect(schema).toContain(
      "CREATE INDEX IF NOT EXISTS `idx_test_v1_book_title` ON `test_v1_book` (`title`);",
    );
    expect(schema).toContain(
      "CREATE INDEX IF NOT EXISTS `idx_test_v1_book_shelf_id` ON `test_v1_book` (`shelf_id`);",
    );
  });

  it("mysql: scalar type mapping uses backticks and engine-specific types", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Types {
        option (protoutil.sql.v1.message).generate = true;
        bool   f_bool   = 1;
        int32  f_int32  = 2;
        int64  f_int64  = 3;
      }
    `,
      { engine: "mysql" },
    );
    const schema = files.get("schema.sql")!;

    expect(schema).not.toContain('"');
    expect(schema).toContain("`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL");
    expect(schema).toContain("`f_bool` TINYINT(1) NOT NULL");
    expect(schema).toContain("`f_int32` INT NOT NULL");
    expect(schema).toContain("`f_int64` BIGINT NOT NULL");
    expect(schema).toContain("`created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
  });
});

// ---------------------------------------------------------------------------
// SQL Server DDL guards — inline unit tests
// ---------------------------------------------------------------------------

describe("schema generator — sqlserver DDL guards", () => {
  it("sqlserver: table with FK and index wraps CREATE TABLE in IF OBJECT_ID guard and index in IF NOT EXISTS guard", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf {
        option (protoutil.sql.v1.message).generate = true;
        string theme = 1;
      }
      message Book {
        option (protoutil.sql.v1.message) = {
          generate: true
          foreign_keys: [{ column: "shelf_id", references_table: "test_v1_shelf", on_delete: FOREIGN_KEY_ACTION_CASCADE }]
        };
        string title = 1 [(protoutil.sql.v1.field).index = true];
      }
    `,
      { engine: "sqlserver" },
    );
    const schema = files.get("schema.sql")!;

    // CREATE TABLE must be guarded with IF OBJECT_ID ... IS NULL / BEGIN / END
    expect(schema).toContain("IF OBJECT_ID(N'test_v1_shelf', N'U') IS NULL");
    expect(schema).toContain("IF OBJECT_ID(N'test_v1_book', N'U') IS NULL");

    // Outer BEGIN/END blocks must be present
    const beginCount = (schema.match(/^BEGIN$/gm) ?? []).length;
    const endCount = (schema.match(/^END$/gm) ?? []).length;
    expect(beginCount).toBe(2);
    expect(endCount).toBe(2);

    // CREATE TABLE inside guard uses double-quotes (not backticks)
    expect(schema).toContain('CREATE TABLE "test_v1_shelf"');
    expect(schema).toContain('CREATE TABLE "test_v1_book"');

    // FK constraint uses double-quoted identifiers
    expect(schema).toContain(
      'CONSTRAINT "fk_test_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_v1_shelf" ("id") ON DELETE CASCADE',
    );

    // Indexes use IF NOT EXISTS guard with sys.indexes lookup
    expect(schema).toContain(
      "IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'test_v1_book') AND name = N'idx_test_v1_book_title')",
    );
    expect(schema).toContain(
      "IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'test_v1_book') AND name = N'idx_test_v1_book_shelf_id')",
    );
    expect(schema).toContain(
      '    CREATE INDEX "idx_test_v1_book_title" ON "test_v1_book" ("title");',
    );
    expect(schema).toContain(
      '    CREATE INDEX "idx_test_v1_book_shelf_id" ON "test_v1_book" ("shelf_id");',
    );
  });

  it("sqlserver: if_not_exists=false emits bare CREATE TABLE and CREATE INDEX without guards", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Shelf {
        option (protoutil.sql.v1.message).generate = true;
        string theme = 1 [(protoutil.sql.v1.field).index = true];
      }
    `,
      { engine: "sqlserver", if_not_exists: "false" },
    );
    const schema = files.get("schema.sql")!;

    expect(schema).not.toContain("IF OBJECT_ID");
    expect(schema).not.toContain("BEGIN");
    expect(schema).not.toContain("END");
    expect(schema).not.toContain("sys.indexes");
    expect(schema).toContain('CREATE TABLE "test_v1_shelf"');
    expect(schema).toContain('CREATE INDEX "idx_test_v1_shelf_theme"');
  });

  it("sqlserver: scalar type mapping uses BIGINT IDENTITY and DATETIMEOFFSET", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      message Types {
        option (protoutil.sql.v1.message).generate = true;
        bool   f_bool   = 1;
        int32  f_int32  = 2;
        int64  f_int64  = 3;
        string f_string = 4;
      }
    `,
      { engine: "sqlserver" },
    );
    const schema = files.get("schema.sql")!;

    expect(schema).toContain('"id" BIGINT IDENTITY(1,1) NOT NULL');
    expect(schema).toContain('"f_bool" BIT NOT NULL');
    expect(schema).toContain('"f_int32" INT NOT NULL');
    expect(schema).toContain('"f_int64" BIGINT NOT NULL');
    expect(schema).toContain('"f_string" NVARCHAR(MAX) NOT NULL');
    expect(schema).toContain('"created_at" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()');
  });
});

// ---------------------------------------------------------------------------
// ENUM_STRATEGY_CHECK_CONSTRAINT — engine-aware quoting bug fix
// ---------------------------------------------------------------------------

describe("schema generator — ENUM_STRATEGY_CHECK_CONSTRAINT quoting", () => {
  it("mysql: CHECK constraint uses backtick-quoted column name", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      enum Status { STATUS_UNSPECIFIED = 0; STATUS_ACTIVE = 1; STATUS_INACTIVE = 2; }
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        Status status = 1 [(protoutil.sql.v1.field).enum_strategy = ENUM_STRATEGY_CHECK_CONSTRAINT];
      }
    `,
      { engine: "mysql" },
    );
    const schema = files.get("schema.sql")!;
    // MySQL must use backtick, not double-quote, in the CHECK expression
    expect(schema).toContain(
      "TEXT CHECK (`status` IN ('STATUS_UNSPECIFIED', 'STATUS_ACTIVE', 'STATUS_INACTIVE')) NOT NULL",
    );
    expect(schema).not.toContain('CHECK ("status"');
  });

  it("sqlserver: CHECK constraint uses double-quoted column name", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      enum Status { STATUS_UNSPECIFIED = 0; STATUS_ACTIVE = 1; STATUS_INACTIVE = 2; }
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        Status status = 1 [(protoutil.sql.v1.field).enum_strategy = ENUM_STRATEGY_CHECK_CONSTRAINT];
      }
    `,
      { engine: "sqlserver" },
    );
    const schema = files.get("schema.sql")!;
    expect(schema).toContain(
      "TEXT CHECK (\"status\" IN ('STATUS_UNSPECIFIED', 'STATUS_ACTIVE', 'STATUS_INACTIVE')) NOT NULL",
    );
  });

  it("CHECK constraint uses resolved column_name override, not proto field name", async () => {
    const files = await generate(
      `
      syntax = "proto3"; package test.v1; import "protoutil/sql/v1/options.proto";
      enum Status { STATUS_UNSPECIFIED = 0; STATUS_ACTIVE = 1; }
      message Book {
        option (protoutil.sql.v1.message).generate = true;
        Status status = 1 [
          (protoutil.sql.v1.field).enum_strategy = ENUM_STRATEGY_CHECK_CONSTRAINT,
          (protoutil.sql.v1.field).column_name = "book_status"
        ];
      }
    `,
      { engine: "postgres" },
    );
    const schema = files.get("schema.sql")!;
    // CHECK should reference "book_status", not the proto field name "status"
    expect(schema).toContain('"book_status" TEXT CHECK ("book_status" IN');
    expect(schema).not.toContain('CHECK ("status"');
  });
});
