import { type DescField, type DescMessage, getOption, ScalarType } from "@bufbuild/protobuf";
import type { Schema } from "@bufbuild/protoplugin";
import {
  EnumStrategy,
  ForeignKeyAction,
  field as fieldOption,
  message as messageOption,
  OneofStrategy,
  oneof as oneofOption,
  PrimaryKeyType,
  TimestampBehavior,
} from "../gen/protoutil/sql/v1/options_pb.js";
import { defaultColumnName, defaultTableName } from "../util/naming.js";
import type { PluginOptions } from "../util/plugin-options.js";
import {
  getJsonColumnType,
  getScalarSqlType,
  getWellKnownSqlType,
  type ProtoScalarType,
  type WellKnownType,
} from "../util/type-mapping.js";

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export function generateSchema(schema: Schema, opts: PluginOptions): void {
  const f = schema.generateFile("schema.sql");

  f.print(`-- schema.sql`);
  f.print(`-- Generated by protoc-gen-sql. DO NOT EDIT.`);
  f.print(`-- Engine: ${opts.engine}`);
  f.print(`--`);
  f.print(`-- Source of truth for schema generation and query generation.`);
  f.print(`-- Re-generate by running: buf generate`);
  f.print(``);

  if (opts.emitCreateSchema && (opts.engine === "postgres" || opts.engine === "sqlserver")) {
    if (opts.engine === "sqlserver") {
      f.print(`IF SCHEMA_ID(N'public') IS NULL EXEC(N'CREATE SCHEMA public');`);
    } else {
      f.print(`CREATE SCHEMA IF NOT EXISTS public;`);
    }
    f.print(``);
  }

  const messages = collectGeneratableMessages(schema);

  if (messages.length === 0) {
    f.print(`-- No messages opted into generation.`);
    f.print(
      `-- Add option (protoutil.sql.v1.message).generate = true to a message to generate a table.`,
    );
    return;
  }

  for (const message of orderByDependency(messages)) {
    emitTable(f, message, opts);
    f.print(``);
  }
}

// ---------------------------------------------------------------------------
// Message collection
// ---------------------------------------------------------------------------

function collectGeneratableMessages(schema: Schema): DescMessage[] {
  const messages: DescMessage[] = [];
  for (const file of schema.files) {
    for (const message of file.messages) {
      if (getOption(message, messageOption).generate) messages.push(message);
    }
  }
  return messages;
}

// ---------------------------------------------------------------------------
// Dependency ordering — topological sort so FK-referenced tables come first
// ---------------------------------------------------------------------------

function orderByDependency(messages: DescMessage[]): DescMessage[] {
  const byTable = new Map<string, DescMessage>();
  for (const msg of messages) {
    const opts = getOption(msg, messageOption);
    byTable.set(opts.tableName || defaultTableName(msg), msg);
  }

  const visited = new Set<string>();
  const ordered: DescMessage[] = [];

  function visit(msg: DescMessage): void {
    const opts = getOption(msg, messageOption);
    const name = opts.tableName || defaultTableName(msg);
    if (visited.has(name)) return;
    visited.add(name);
    for (const fk of opts.foreignKeys) {
      const dep = byTable.get(fk.referencesTable);
      if (dep) visit(dep);
    }
    ordered.push(msg);
  }

  for (const msg of messages) visit(msg);
  return ordered;
}

// ---------------------------------------------------------------------------
// Identifier quoting
// ---------------------------------------------------------------------------

// MySQL uses backticks; all other supported engines use double quotes.
// SQL Server also accepts double quotes when QUOTED_IDENTIFIER is ON (the
// default), but backticks are MySQL-only.
function q(name: string, opts: PluginOptions): string {
  return opts.engine === "mysql" ? `\`${name}\`` : `"${name}"`;
}

// ---------------------------------------------------------------------------
// Table emission
// ---------------------------------------------------------------------------

function emitTable(
  f: ReturnType<Schema["generateFile"]>,
  message: DescMessage,
  opts: PluginOptions,
): void {
  const msgOpts = getOption(message, messageOption);
  const tableName = msgOpts.tableName || defaultTableName(message);

  f.print(`-- ${message.typeName}`);

  if (opts.ifNotExists) {
    emitCreateTableGuardOpen(f, tableName, opts);
  } else {
    f.print(`CREATE TABLE ${q(tableName, opts)} (`);
  }

  const lines: string[] = [];

  // Primary key
  lines.push(`    ${q("id", opts)} ${pkColumnDef(msgOpts.primaryKey, opts)} NOT NULL`);

  // FK columns — before proto fields
  for (const fk of msgOpts.foreignKeys) {
    lines.push(`    ${q(fk.column, opts)} ${fkColumnType(msgOpts.primaryKey, opts)} NOT NULL`);
  }

  // Proto fields (non-oneof)
  for (const field of message.fields) {
    if (field.oneof) continue;
    const line = emitColumn(field, opts);
    if (line !== null) lines.push(line);
  }

  // Oneof groups
  const oneofsSeen = new Set<string>();
  for (const field of message.fields) {
    if (!field.oneof) continue;
    if (oneofsSeen.has(field.oneof.name)) continue;
    oneofsSeen.add(field.oneof.name);
    lines.push(...emitOneof(field.oneof, message, opts));
  }

  // Extra columns
  for (const col of msgOpts.extraColumns) {
    const engineType = col.typeOverrides[opts.engine] ?? col.columnType;
    const nullClause = col.nullable ? "NULL" : "NOT NULL";
    const defaultClause = col.default ? ` DEFAULT ${col.default}` : "";
    const checkClause = col.check ? ` CHECK (${col.check})` : "";
    lines.push(
      `    ${q(col.columnName, opts)} ${engineType} ${nullClause}${defaultClause}${checkClause}`,
    );
  }

  // Timestamps
  const tsb = msgOpts.timestamps;
  const emitCreated =
    tsb === TimestampBehavior.UNSPECIFIED ||
    tsb === TimestampBehavior.BOTH ||
    tsb === TimestampBehavior.CREATED_ONLY;
  const emitUpdated =
    tsb === TimestampBehavior.UNSPECIFIED ||
    tsb === TimestampBehavior.BOTH ||
    tsb === TimestampBehavior.UPDATED_ONLY;

  if (emitCreated)
    lines.push(
      `    ${q("created_at", opts)} ${timestampType(opts)} NOT NULL DEFAULT ${timestampDefault(opts)}`,
    );
  if (emitUpdated)
    lines.push(
      `    ${q("updated_at", opts)} ${timestampType(opts)} NOT NULL DEFAULT ${timestampDefault(opts)}`,
    );

  // PRIMARY KEY constraint
  lines.push(`    PRIMARY KEY (${q("id", opts)})`);

  // FK constraints
  for (const fk of msgOpts.foreignKeys) {
    const refCol = fk.referencesColumn || "id";
    const onDelete = fkAction(fk.onDelete);
    const onUpdate = fkAction(fk.onUpdate);
    lines.push(
      `    CONSTRAINT ${q(`fk_${tableName}_${fk.column}`, opts)} ` +
        `FOREIGN KEY (${q(fk.column, opts)}) ` +
        `REFERENCES ${q(fk.referencesTable, opts)} (${q(refCol, opts)})` +
        (onDelete ? ` ON DELETE ${onDelete}` : "") +
        (onUpdate ? ` ON UPDATE ${onUpdate}` : ""),
    );
  }

  // Composite unique constraints
  for (const uc of msgOpts.uniqueConstraints) {
    const cols = uc
      .split(",")
      .map((c) => q(c.trim(), opts))
      .join(", ");
    const name = uc.replace(/[,\s]+/g, "_");
    lines.push(`    CONSTRAINT ${q(`uq_${tableName}_${name}`, opts)} UNIQUE (${cols})`);
  }

  f.print(lines.join(",\n"));

  if (opts.ifNotExists && opts.engine === "sqlserver") {
    f.print(`);`);
    f.print(`END`);
  } else {
    f.print(`);`);
  }

  // Indexes
  for (const field of message.fields) {
    const fOpts = getOption(field, fieldOption);
    if (!fOpts.omit && fOpts.index) {
      const colName = fOpts.columnName || defaultColumnName(field);
      emitIndex(f, tableName, `idx_${tableName}_${colName}`, [colName], false, opts);
    }
  }
  for (const fk of msgOpts.foreignKeys) {
    if (!fk.skipIndex) {
      emitIndex(f, tableName, `idx_${tableName}_${fk.column}`, [fk.column], false, opts);
    }
  }
  for (const idx of msgOpts.indexes) {
    const cols = idx.split(",").map((c) => c.trim());
    const name = idx.replace(/[,\s]+/g, "_");
    emitIndex(f, tableName, `idx_${tableName}_${name}`, cols, false, opts);
  }
  for (const col of msgOpts.extraColumns) {
    if (col.index)
      emitIndex(f, tableName, `idx_${tableName}_${col.columnName}`, [col.columnName], false, opts);
    if (col.unique)
      emitIndex(f, tableName, `uq_${tableName}_${col.columnName}`, [col.columnName], true, opts);
  }
}

// ---------------------------------------------------------------------------
// Engine-specific CREATE TABLE / CREATE INDEX guards
// ---------------------------------------------------------------------------

function emitCreateTableGuardOpen(
  f: ReturnType<Schema["generateFile"]>,
  tableName: string,
  opts: PluginOptions,
): void {
  switch (opts.engine) {
    case "sqlserver":
      f.print(`IF OBJECT_ID(N'${tableName}', N'U') IS NULL`);
      f.print(`BEGIN`);
      f.print(`CREATE TABLE ${q(tableName, opts)} (`);
      break;
    default:
      // postgres, mysql, sqlite all support IF NOT EXISTS natively
      f.print(`CREATE TABLE IF NOT EXISTS ${q(tableName, opts)} (`);
  }
}

function emitIndex(
  f: ReturnType<Schema["generateFile"]>,
  tableName: string,
  indexName: string,
  cols: string[],
  unique: boolean,
  opts: PluginOptions,
): void {
  const uniqueKw = unique ? " UNIQUE" : "";
  const colList = cols.map((c) => q(c, opts)).join(", ");

  switch (opts.engine) {
    case "sqlserver":
      if (opts.ifNotExists) {
        f.print(
          `IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'${tableName}') AND name = N'${indexName}')`,
        );
        f.print(
          `    CREATE${uniqueKw} INDEX ${q(indexName, opts)} ON ${q(tableName, opts)} (${colList});`,
        );
      } else {
        f.print(
          `CREATE${uniqueKw} INDEX ${q(indexName, opts)} ON ${q(tableName, opts)} (${colList});`,
        );
      }
      break;
    default:
      // postgres, sqlite: CREATE INDEX IF NOT EXISTS is valid
      // mysql 8.0+: CREATE INDEX IF NOT EXISTS is valid; for older mysql
      // the ifNotExists option should be set to false
      f.print(
        `CREATE${uniqueKw} INDEX${opts.ifNotExists ? " IF NOT EXISTS" : ""} ${q(indexName, opts)} ON ${q(tableName, opts)} (${colList});`,
      );
  }
}

// ---------------------------------------------------------------------------
// Column emission
// ---------------------------------------------------------------------------

function emitColumn(field: DescField, opts: PluginOptions): string | null {
  const fOpts = getOption(field, fieldOption);
  if (fOpts.omit) return null;

  const colName = fOpts.columnName || defaultColumnName(field);
  const engineOverride = fOpts.typeOverrides[opts.engine];
  const sqlType =
    engineOverride || fOpts.columnType || resolveColumnType(field, opts, fOpts.enumStrategy);
  if (sqlType === null) return null;

  const nullClause = fOpts.nullable ? "NULL" : "NOT NULL";
  const defaultClause = fOpts.default ? ` DEFAULT ${fOpts.default}` : "";
  const checkClause = fOpts.check ? ` CHECK (${fOpts.check})` : "";

  return `    ${q(colName, opts)} ${sqlType} ${nullClause}${defaultClause}${checkClause}`;
}

// ---------------------------------------------------------------------------
// Oneof emission
// ---------------------------------------------------------------------------

function emitOneof(oneof: DescField["oneof"], message: DescMessage, opts: PluginOptions): string[] {
  if (!oneof) return [];
  const oneofOpts = getOption(oneof, oneofOption);
  const strategy: OneofStrategy =
    oneofOpts.strategy !== OneofStrategy.UNSPECIFIED
      ? oneofOpts.strategy
      : pluginOneofStrategy(opts);

  const fields = message.fields.filter((f) => f.oneof?.name === oneof.name);

  switch (strategy) {
    case OneofStrategy.NULLABLE_COLS: {
      const lines: string[] = [];
      for (const f of fields) {
        const sqlType = resolveColumnType(f, opts, EnumStrategy.UNSPECIFIED) ?? "TEXT";
        lines.push(`    ${q(defaultColumnName(f), opts)} ${sqlType} NULL`);
      }
      if (fields.length > 1) {
        const checks = fields
          .map((f) => `${q(defaultColumnName(f), opts)} IS NOT NULL`)
          .join(" AND ");
        lines.push(`    CONSTRAINT ${q(`chk_${oneof.name}_oneof`, opts)} CHECK (NOT (${checks}))`);
      }
      return lines;
    }
    case OneofStrategy.TYPE_COLUMN:
      return [
        `    ${q(`${oneof.name}_type`, opts)} TEXT NULL`,
        `    ${q(`${oneof.name}_value`, opts)} TEXT NULL`,
      ];
    case OneofStrategy.JSON_COLUMN:
      return [`    ${q(oneof.name, opts)} ${getJsonColumnType(opts.engine)} NULL`];
    default:
      return [];
  }
}

// ---------------------------------------------------------------------------
// Type resolution
// ---------------------------------------------------------------------------

function resolveColumnType(
  field: DescField,
  opts: PluginOptions,
  enumStrategy: EnumStrategy,
): string | null {
  if (field.fieldKind === "list" || field.fieldKind === "map") {
    return getJsonColumnType(opts.engine);
  }
  if (field.fieldKind === "scalar") {
    return getScalarSqlType(opts.engine, scalarTypeName(field.scalar));
  }
  if (field.fieldKind === "message") {
    const wkt = getWellKnownSqlType(opts.engine, field.message.typeName as WellKnownType);
    return wkt ?? getJsonColumnType(opts.engine);
  }
  if (field.fieldKind === "enum") {
    return resolveEnumType(field, opts, enumStrategy);
  }
  return null;
}

function resolveEnumType(field: DescField, opts: PluginOptions, strategy: EnumStrategy): string {
  const effective = strategy === EnumStrategy.UNSPECIFIED ? EnumStrategy.NAME : strategy;

  switch (effective) {
    case EnumStrategy.INT:
      return opts.engine === "mysql" ? "INT" : "INTEGER";

    case EnumStrategy.CHECK_CONSTRAINT: {
      const values = field.enum?.values.map((v) => `'${v.name}'`).join(", ");
      const colName = getOption(field, fieldOption).columnName || defaultColumnName(field);
      return `TEXT CHECK (${q(colName, opts)} IN (${values}))`;
    }

    case EnumStrategy.NATIVE_TYPE:
      // postgres: reference the CREATE TYPE emitted separately
      // other engines: fall back to NAME
      return opts.engine === "postgres"
        ? `"${field.enum?.typeName.toLowerCase().replace(/\./g, "_")}"`
        : "TEXT";

    case EnumStrategy.NAME:
      return "TEXT";
  }
}

// ---------------------------------------------------------------------------
// Primary key helpers
// ---------------------------------------------------------------------------

function pkColumnDef(pkType: PrimaryKeyType, opts: PluginOptions): string {
  if (pkType === PrimaryKeyType.UUID) {
    switch (opts.engine) {
      case "postgres":
        return "UUID DEFAULT gen_random_uuid()";
      case "mysql":
        return "CHAR(36) DEFAULT (UUID())";
      case "sqlite":
        return "TEXT DEFAULT (lower(hex(randomblob(16))))";
      case "sqlserver":
        return "UNIQUEIDENTIFIER DEFAULT NEWID()";
    }
  }
  switch (opts.engine) {
    case "postgres":
      return "BIGSERIAL";
    case "mysql":
      return "BIGINT UNSIGNED AUTO_INCREMENT";
    case "sqlite":
      return "INTEGER";
    case "sqlserver":
      return "BIGINT IDENTITY(1,1)";
  }
}

// FK columns referencing a UUID PK should use the matching type
function fkColumnType(pkType: PrimaryKeyType, opts: PluginOptions): string {
  if (pkType === PrimaryKeyType.UUID) {
    switch (opts.engine) {
      case "postgres":
        return "UUID";
      case "mysql":
        return "CHAR(36)";
      case "sqlite":
        return "TEXT";
      case "sqlserver":
        return "UNIQUEIDENTIFIER";
    }
  }
  switch (opts.engine) {
    case "postgres":
      return "BIGINT";
    case "mysql":
      return "BIGINT UNSIGNED";
    case "sqlite":
      return "INTEGER";
    case "sqlserver":
      return "BIGINT";
  }
}

// ---------------------------------------------------------------------------
// Engine-specific helpers
// ---------------------------------------------------------------------------

function timestampType(opts: PluginOptions): string {
  switch (opts.engine) {
    case "postgres":
      return "TIMESTAMPTZ";
    case "mysql":
      return "DATETIME(6)";
    case "sqlite":
      return "TEXT";
    case "sqlserver":
      return "DATETIMEOFFSET";
  }
}

function timestampDefault(opts: PluginOptions): string {
  switch (opts.engine) {
    case "postgres":
      return "now()";
    case "mysql":
      return "CURRENT_TIMESTAMP(6)";
    case "sqlite":
      return "(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))";
    case "sqlserver":
      return "SYSDATETIMEOFFSET()";
  }
}

function fkAction(action: ForeignKeyAction): string {
  switch (action) {
    case ForeignKeyAction.CASCADE:
      return "CASCADE";
    case ForeignKeyAction.RESTRICT:
      return "RESTRICT";
    case ForeignKeyAction.SET_NULL:
      return "SET NULL";
    case ForeignKeyAction.NO_ACTION:
      return "NO ACTION";
    default:
      return "";
  }
}

export function pluginOneofStrategy(opts: PluginOptions): OneofStrategy {
  switch (opts.oneofStrategy) {
    case "nullable_columns":
      return OneofStrategy.NULLABLE_COLS;
    case "type_column":
      return OneofStrategy.TYPE_COLUMN;
    case "json_column":
      return OneofStrategy.JSON_COLUMN;
  }
}

function scalarTypeName(scalar: ScalarType): ProtoScalarType {
  const map: Record<ScalarType, ProtoScalarType> = {
    [ScalarType.STRING]: "string",
    [ScalarType.BOOL]: "bool",
    [ScalarType.BYTES]: "bytes",
    [ScalarType.DOUBLE]: "double",
    [ScalarType.FLOAT]: "float",
    [ScalarType.INT32]: "int32",
    [ScalarType.INT64]: "int64",
    [ScalarType.UINT32]: "uint32",
    [ScalarType.UINT64]: "uint64",
    [ScalarType.SINT32]: "sint32",
    [ScalarType.SINT64]: "sint64",
    [ScalarType.FIXED32]: "fixed32",
    [ScalarType.FIXED64]: "fixed64",
    [ScalarType.SFIXED32]: "sfixed32",
    [ScalarType.SFIXED64]: "sfixed64",
  };
  return map[scalar];
}
