-- schema.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: sqlserver
--
-- Source of truth for schema generation and query generation.
-- Re-generate by running: buf generate

-- test.library.v1.Shelf
IF OBJECT_ID(N'test_library_v1_shelf', N'U') IS NULL
BEGIN
CREATE TABLE "test_library_v1_shelf" (
    "id" BIGINT IDENTITY(1,1) NOT NULL,
    "theme" NVARCHAR(MAX) NOT NULL,
    "created_at" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    "updated_at" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    PRIMARY KEY ("id")
);
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'test_library_v1_shelf') AND name = N'idx_test_library_v1_shelf_theme')
    CREATE INDEX "idx_test_library_v1_shelf_theme" ON "test_library_v1_shelf" ("theme");

-- test.library.v1.Book
IF OBJECT_ID(N'test_library_v1_book', N'U') IS NULL
BEGIN
CREATE TABLE "test_library_v1_book" (
    "id" BIGINT IDENTITY(1,1) NOT NULL,
    "shelf_id" BIGINT NOT NULL,
    "author" NVARCHAR(MAX) NOT NULL,
    "title" NVARCHAR(MAX) NOT NULL,
    "read" BIT NOT NULL,
    "created_at" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    "updated_at" DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_test_library_v1_book_shelf_id" FOREIGN KEY ("shelf_id") REFERENCES "test_library_v1_shelf" ("id") ON DELETE CASCADE
);
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'test_library_v1_book') AND name = N'idx_test_library_v1_book_author')
    CREATE INDEX "idx_test_library_v1_book_author" ON "test_library_v1_book" ("author");
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'test_library_v1_book') AND name = N'idx_test_library_v1_book_shelf_id')
    CREATE INDEX "idx_test_library_v1_book_shelf_id" ON "test_library_v1_book" ("shelf_id");