-- test_library_v1_shelf.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: sqlserver
-- Source message: test.library.v1.Shelf
--
-- Add custom queries in queries/custom/ alongside this file.

-- name: GetTestLibraryV1Shelf :one
SELECT TOP 1 "id", "theme", "created_at", "updated_at"
FROM "test_library_v1_shelf"
WHERE "id" = @p1;

-- name: ListTestLibraryV1Shelf :many
SELECT "id", "theme", "created_at", "updated_at"
FROM "test_library_v1_shelf"
ORDER BY "id";

-- name: CreateTestLibraryV1Shelf :execresult
INSERT INTO "test_library_v1_shelf" ("theme")
VALUES (@p1);

-- name: GetTestLibraryV1ShelfByLastInsert :one
SELECT TOP 1 * FROM "test_library_v1_shelf" WHERE "id" = SCOPE_IDENTITY();

-- name: UpdateTestLibraryV1Shelf :exec
UPDATE "test_library_v1_shelf"
SET
    "theme" = @p1,
    "updated_at" = SYSDATETIMEOFFSET()
WHERE "id" = @p2;

-- name: DeleteTestLibraryV1Shelf :exec
DELETE FROM "test_library_v1_shelf"
WHERE "id" = @p1;