-- test_library_v1_book.sql
-- Generated by protoc-gen-sql. DO NOT EDIT.
-- Engine: sqlserver
-- Source message: test.library.v1.Book
--
-- Add custom queries in queries/custom/ alongside this file.

-- name: GetTestLibraryV1Book :one
SELECT TOP 1 "id", "shelf_id", "author", "title", "read", "created_at", "updated_at"
FROM "test_library_v1_book"
WHERE "id" = @p1;

-- name: ListTestLibraryV1Book :many
SELECT "id", "shelf_id", "author", "title", "read", "created_at", "updated_at"
FROM "test_library_v1_book"
ORDER BY "id";

-- name: CreateTestLibraryV1Book :execresult
INSERT INTO "test_library_v1_book" ("shelf_id", "author", "title", "read")
VALUES (@p1, @p2, @p3, @p4);

-- name: GetTestLibraryV1BookByLastInsert :one
SELECT TOP 1 * FROM "test_library_v1_book" WHERE "id" = SCOPE_IDENTITY();

-- name: UpdateTestLibraryV1Book :exec
UPDATE "test_library_v1_book"
SET
    "shelf_id" = @p1,
    "author" = @p2,
    "title" = @p3,
    "read" = @p4,
    "updated_at" = SYSDATETIMEOFFSET()
WHERE "id" = @p5;

-- name: DeleteTestLibraryV1Book :exec
DELETE FROM "test_library_v1_book"
WHERE "id" = @p1;